using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Selectum.Models
{
    public class ModelDataInitializer
    {

        public List<User> InitializeUsers()
        {
            var users = new List<User>
            {
                new User {UserName="hunt27"},
                new User {UserName="hubie39"},
                new User {UserName="coot77"},
                new User {UserName="wally4"}
            };

            return users;
        }

        public List<UserToUserProfile> InitializeUserToUserProfiles()
        {
            var users = new List<UserToUserProfile>
            {
                new UserToUserProfile {UserId = 1, UserProfileId=1},
                new UserToUserProfile {UserId = 2, UserProfileId=2},
                new UserToUserProfile {UserId = 3, UserProfileId=3},
                new UserToUserProfile {UserId = 4, UserProfileId=4}
            };

            return users;
        }

        public List<Team> InitializeTeams()
        {
            var teams = new List<Team>
            {
                new Team {TeamId=1,TeamLongName="No Bet",TeamShortName="X  ",TeamOtherName="No Bet"},
                new Team {TeamId=2,TeamLongName="NY Giants",TeamShortName="NYG",TeamOtherName="Giants"},
                new Team {TeamId=3,TeamLongName="New England",TeamShortName="NE ",TeamOtherName="Patriots"},
                new Team {TeamId=4,TeamLongName="Minnesota",TeamShortName="MIN",TeamOtherName="Vikings"},
                new Team {TeamId=5,TeamLongName="New Orleans",TeamShortName="NO ",TeamOtherName="Saints"},
                new Team {TeamId=6,TeamLongName="Buffalo",TeamShortName="BUF",TeamOtherName="Bills"},
                new Team {TeamId=7,TeamLongName="Philadelphia",TeamShortName="PHI",TeamOtherName="Eagles"},
                new Team {TeamId=8,TeamLongName="Oakland",TeamShortName="OAK",TeamOtherName="Raiders"},
                new Team {TeamId=9,TeamLongName="Cincinnati",TeamShortName="CIN",TeamOtherName="Bengals"},
                new Team {TeamId=10,TeamLongName="Houston",TeamShortName="HOU",TeamOtherName="Texans"},
                new Team {TeamId=11,TeamLongName="Dallas",TeamShortName="DAL",TeamOtherName="Cowboys"},
                new Team {TeamId=12,TeamLongName="Washington",TeamShortName="WAS",TeamOtherName="Redskins"},
                new Team {TeamId=13,TeamLongName="Pittsburgh",TeamShortName="PIT",TeamOtherName="Steelers"},
                new Team {TeamId=14,TeamLongName="San Diego",TeamShortName="SD ",TeamOtherName="Chargers"},
                new Team {TeamId=15,TeamLongName="San Francisco",TeamShortName="SF ",TeamOtherName="49ers"},
                new Team {TeamId=16,TeamLongName="Atlanta",TeamShortName="ATL",TeamOtherName="Falcons"},
                new Team {TeamId=17,TeamLongName="Carolina",TeamShortName="CAR",TeamOtherName="Panthers"},
                new Team {TeamId=18,TeamLongName="Chicago",TeamShortName="CHI",TeamOtherName="Bears"},
                new Team {TeamId=19,TeamLongName="Detroit",TeamShortName="DET",TeamOtherName="Lions"},
                new Team {TeamId=20,TeamLongName="NY Jets",TeamShortName="NYJ",TeamOtherName="Jets"},
                new Team {TeamId=21,TeamLongName="Indianapolis",TeamShortName="IND",TeamOtherName="Colts"},
                new Team {TeamId=22,TeamLongName="Baltimore",TeamShortName="BAL",TeamOtherName="Ravens"},
                new Team {TeamId=23,TeamLongName="Kansas City",TeamShortName="KC ",TeamOtherName="Chiefs"},
                new Team {TeamId=24,TeamLongName="Seattle",TeamShortName="SEA",TeamOtherName="Seahawks"},
                new Team {TeamId=25,TeamLongName="Arizona",TeamShortName="ARI",TeamOtherName="Cardinals"},
                new Team {TeamId=26,TeamLongName="Denver",TeamShortName="DEN",TeamOtherName="Broncos"},
                new Team {TeamId=27,TeamLongName="Tampa Bay",TeamShortName="TB ",TeamOtherName="Buccaneers"},
                new Team {TeamId=28,TeamLongName="Miami",TeamShortName="MIA",TeamOtherName="Dolphins"},
                new Team {TeamId=29,TeamLongName="Cleveland",TeamShortName="CLE",TeamOtherName="Browns"},
                new Team {TeamId=30,TeamLongName="Jacksonville",TeamShortName="JAC",TeamOtherName="Jaguars"},
                new Team {TeamId=31,TeamLongName="St. Louis",TeamShortName="STL",TeamOtherName="Rams"},
                new Team {TeamId=32,TeamLongName="Tennessee",TeamShortName="TEN",TeamOtherName="Titans"},
                new Team {TeamId=33,TeamLongName="Green Bay",TeamShortName="GB ",TeamOtherName="Packers"}
            };

            return teams;
        }

        public List<GameFilter> InitializeGameFilters()
        {
            var gameFilters = new List<GameFilter>
            {
                new GameFilter { GameFilterName = "Week 01", GameFilterStartDate = Convert.ToDateTime("9/4/2012"), GameFilterEndDate = Convert.ToDateTime("9/10/2012 23:59:59.997"), GameFilterEnabled=false, GameFilterAvailable=false },
                new GameFilter { GameFilterName = "Week 02", GameFilterStartDate = Convert.ToDateTime("9/11/2012"), GameFilterEndDate = Convert.ToDateTime("9/17/2012 23:59:59.997"), GameFilterEnabled=false, GameFilterAvailable=false },
                new GameFilter { GameFilterName = "Week 03", GameFilterStartDate = Convert.ToDateTime("9/18/2012"), GameFilterEndDate = Convert.ToDateTime("9/24/2012 23:59:59.997"), GameFilterEnabled=false, GameFilterAvailable=false },
                new GameFilter { GameFilterName = "Week 04", GameFilterStartDate = Convert.ToDateTime("9/25/2012"), GameFilterEndDate = Convert.ToDateTime("10/1/2012 23:59:59.997"), GameFilterEnabled=false, GameFilterAvailable=false },
                new GameFilter { GameFilterName = "Week 05", GameFilterStartDate = Convert.ToDateTime("10/2/2012"), GameFilterEndDate = Convert.ToDateTime("10/8/2012 23:59:59.997"), GameFilterEnabled=true, GameFilterAvailable=true },
                new GameFilter { GameFilterName = "Week 06", GameFilterStartDate = Convert.ToDateTime("10/9/2012"), GameFilterEndDate = Convert.ToDateTime("10/15/2012 23:59:59.997"), GameFilterEnabled=true, GameFilterAvailable=true },
                new GameFilter { GameFilterName = "Week 07", GameFilterStartDate = Convert.ToDateTime("10/16/2012"), GameFilterEndDate = Convert.ToDateTime("10/22/2012 23:59:59.997"), GameFilterEnabled=true, GameFilterAvailable=true },
                new GameFilter { GameFilterName = "Week 08", GameFilterStartDate = Convert.ToDateTime("10/23/2012"), GameFilterEndDate = Convert.ToDateTime("10/29/2012 23:59:59.997"), GameFilterEnabled=true, GameFilterAvailable=true },
                new GameFilter { GameFilterName = "Week 09", GameFilterStartDate = Convert.ToDateTime("10/30/2012"), GameFilterEndDate = Convert.ToDateTime("11/5/2012 23:59:59.997"), GameFilterEnabled=true, GameFilterAvailable=true },
                new GameFilter { GameFilterName = "Week 10", GameFilterStartDate = Convert.ToDateTime("11/6/2012"), GameFilterEndDate = Convert.ToDateTime("11/12/2012 23:59:59.997"), GameFilterEnabled=true, GameFilterAvailable=true },
                new GameFilter { GameFilterName = "Week 11", GameFilterStartDate = Convert.ToDateTime("11/13/2012"), GameFilterEndDate = Convert.ToDateTime("11/19/2012 23:59:59.997"), GameFilterEnabled=true, GameFilterAvailable=true },
                new GameFilter { GameFilterName = "Week 12", GameFilterStartDate = Convert.ToDateTime("11/20/2012"), GameFilterEndDate = Convert.ToDateTime("11/26/2012 23:59:59.997"), GameFilterEnabled=true, GameFilterAvailable=false },
                new GameFilter { GameFilterName = "Week 13", GameFilterStartDate = Convert.ToDateTime("11/27/2012"), GameFilterEndDate = Convert.ToDateTime("12/3/2012 23:59:59.997"), GameFilterEnabled=true, GameFilterAvailable=false },
                new GameFilter { GameFilterName = "Week 14", GameFilterStartDate = Convert.ToDateTime("12/4/2012"), GameFilterEndDate = Convert.ToDateTime("12/10/2012 23:59:59.997"), GameFilterEnabled=true, GameFilterAvailable=false },
                new GameFilter { GameFilterName = "Week 15", GameFilterStartDate = Convert.ToDateTime("12/11/2012"), GameFilterEndDate = Convert.ToDateTime("12/17/2012 23:59:59.997"), GameFilterEnabled=true, GameFilterAvailable=false },
                new GameFilter { GameFilterName = "Week 16", GameFilterStartDate = Convert.ToDateTime("12/18/2012"), GameFilterEndDate = Convert.ToDateTime("12/24/2012 23:59:59.997"), GameFilterEnabled=true, GameFilterAvailable=false },
                new GameFilter { GameFilterName = "Week 17", GameFilterStartDate = Convert.ToDateTime("12/25/2012"), GameFilterEndDate = Convert.ToDateTime("12/31/2012 23:59:59.997"), GameFilterEnabled=true, GameFilterAvailable=false },

            };

            return gameFilters;
        }

        public List<Game> InitializeGames()
        {
            var games = new List<Game>
            {
                new Game {  GameFilterId = 2,GameDateTime= Convert.ToDateTime("2012-09-13 20:20:00"), Team1Id= 33,Team2Id= 18,HomeTeam=1}, 
                new Game {  GameFilterId = 2,GameDateTime= Convert.ToDateTime("2012-09-16 13:00:00"), Team1Id= 2,Team2Id= 27,HomeTeam=1}, 
                new Game {  GameFilterId = 2,GameDateTime= Convert.ToDateTime("2012-09-16 13:00:00"), Team1Id= 3,Team2Id= 25,HomeTeam=1}, 
                new Game {  GameFilterId = 2,GameDateTime= Convert.ToDateTime("2012-09-16 13:00:00"), Team1Id= 4,Team2Id= 21,HomeTeam=2 }, 
                new Game {  GameFilterId = 2,GameDateTime= Convert.ToDateTime("2012-09-16 13:00:00"), Team1Id= 5,Team2Id= 17,HomeTeam=2 }, 
                new Game {  GameFilterId = 2,GameDateTime= Convert.ToDateTime("2012-09-16 13:00:00"), Team1Id= 6,Team2Id= 23,HomeTeam=1}, 
                new Game {  GameFilterId = 2,GameDateTime= Convert.ToDateTime("2012-09-16 13:00:00"), Team1Id= 7,Team2Id= 22,HomeTeam=1}, 
                new Game {  GameFilterId = 2,GameDateTime= Convert.ToDateTime("2012-09-16 13:00:00"), Team1Id= 8,Team2Id= 28,HomeTeam=2 }, 
                new Game {  GameFilterId = 2,GameDateTime= Convert.ToDateTime("2012-09-16 13:00:00"), Team1Id= 9,Team2Id= 29,HomeTeam=1},
                new Game {  GameFilterId = 2,GameDateTime= Convert.ToDateTime("2012-09-16 13:00:00"), Team1Id= 10,Team2Id= 30,HomeTeam=2 }, 
                new Game {  GameFilterId = 2,GameDateTime= Convert.ToDateTime("2012-09-16 16:05:00"), Team1Id= 11,Team2Id= 24,HomeTeam=2 },
                new Game {  GameFilterId = 2,GameDateTime= Convert.ToDateTime("2012-09-16 16:05:00"), Team1Id= 12,Team2Id= 31,HomeTeam=2 }, 
                new Game {  GameFilterId = 2,GameDateTime= Convert.ToDateTime("2012-09-16 16:25:00"), Team1Id= 13,Team2Id= 20,HomeTeam=1}, 
                new Game {  GameFilterId = 2,GameDateTime= Convert.ToDateTime("2012-09-16 16:25:00"), Team1Id= 14,Team2Id= 32,HomeTeam=1}, 
                new Game {  GameFilterId = 2,GameDateTime= Convert.ToDateTime("2012-09-16 20:20:00"), Team1Id= 15,Team2Id= 19,HomeTeam=1},
                new Game {  GameFilterId = 2,GameDateTime= Convert.ToDateTime("2012-09-17 20:35:00"), Team1Id= 16,Team2Id= 26,HomeTeam=1}, 
                new Game {  GameFilterId = 3,GameDateTime= Convert.ToDateTime("2012-09-20 20:20:00"), Team1Id= 17,Team2Id= 2,HomeTeam=1}, 
                new Game {  GameFilterId = 3,GameDateTime= Convert.ToDateTime("2012-09-23 13:00:00"), Team1Id= 18,Team2Id= 31,HomeTeam=1},
                new Game {  GameFilterId = 3,GameDateTime= Convert.ToDateTime("2012-09-23 13:00:00"), Team1Id= 11,Team2Id= 27,HomeTeam=1}, 
                new Game {  GameFilterId = 3,GameDateTime= Convert.ToDateTime("2012-09-23 13:00:00"), Team1Id= 15,Team2Id= 4,HomeTeam=2 }, 
                new Game {  GameFilterId = 3,GameDateTime= Convert.ToDateTime("2012-09-23 13:00:00"), Team1Id= 19,Team2Id= 32,HomeTeam=2 }, 
                new Game {  GameFilterId = 3,GameDateTime= Convert.ToDateTime("2012-09-23 13:00:00"), Team1Id= 12,Team2Id= 9,HomeTeam=1}, 
                new Game {  GameFilterId = 3,GameDateTime= Convert.ToDateTime("2012-09-23 13:00:00"), Team1Id= 20,Team2Id= 28,HomeTeam=2 }, 
                new Game {  GameFilterId = 3,GameDateTime= Convert.ToDateTime("2012-09-23 13:00:00"), Team1Id= 5,Team2Id= 23,HomeTeam=1}, 
                new Game {  GameFilterId = 3,GameDateTime= Convert.ToDateTime("2012-09-23 13:00:00"), Team1Id= 6,Team2Id= 29,HomeTeam=2 }, 
                new Game {  GameFilterId = 3,GameDateTime= Convert.ToDateTime("2012-09-23 13:00:00"), Team1Id= 21,Team2Id= 30,HomeTeam=1},
                new Game {  GameFilterId = 3,GameDateTime= Convert.ToDateTime("2012-09-23 16:05:00"), Team1Id= 7,Team2Id= 25,HomeTeam=2 },
                new Game {  GameFilterId = 3,GameDateTime= Convert.ToDateTime("2012-09-23 16:05:00"), Team1Id= 14,Team2Id= 16,HomeTeam=1}, 
                new Game {  GameFilterId = 3,GameDateTime= Convert.ToDateTime("2012-09-23 16:25:00"), Team1Id= 10,Team2Id= 26,HomeTeam=2 }, 
                new Game {  GameFilterId = 3,GameDateTime= Convert.ToDateTime("2012-09-23 16:25:00"), Team1Id= 13,Team2Id= 8,HomeTeam=2 },
                new Game {  GameFilterId = 3,GameDateTime= Convert.ToDateTime("2012-09-23 20:25:00"), Team1Id= 22,Team2Id= 3,HomeTeam=1}, 
                new Game {  GameFilterId = 3,GameDateTime= Convert.ToDateTime("2012-09-24 20:35:00"), Team1Id= 33,Team2Id= 24,HomeTeam=2 },
                new Game {  GameFilterId = 4,GameDateTime= Convert.ToDateTime("2012-09-27 20:20:00"), Team1Id= 22,Team2Id= 29,HomeTeam=1},
                new Game {  GameFilterId = 4,GameDateTime= Convert.ToDateTime("2012-09-30 13:00:00"), Team1Id= 3,Team2Id= 6,HomeTeam=2 }, 
                new Game {  GameFilterId = 4,GameDateTime= Convert.ToDateTime("2012-09-30 13:00:00"), Team1Id= 19,Team2Id= 4,HomeTeam=1}, 
                new Game {  GameFilterId = 4,GameDateTime= Convert.ToDateTime("2012-09-30 13:00:00"), Team1Id= 16,Team2Id= 17,HomeTeam=1},
                new Game {  GameFilterId = 4,GameDateTime= Convert.ToDateTime("2012-09-30 13:00:00"), Team1Id= 15,Team2Id= 20,HomeTeam=2 },
                new Game {  GameFilterId = 4,GameDateTime= Convert.ToDateTime("2012-09-30 13:00:00"), Team1Id= 23,Team2Id= 14,HomeTeam=1},
                new Game {  GameFilterId = 4,GameDateTime= Convert.ToDateTime("2012-09-30 13:00:00"), Team1Id= 10,Team2Id= 32,HomeTeam=1}, 
                new Game {  GameFilterId = 4,GameDateTime= Convert.ToDateTime("2012-09-30 13:00:00"), Team1Id= 24,Team2Id= 31,HomeTeam=2 },
                new Game {  GameFilterId = 4,GameDateTime= Convert.ToDateTime("2012-09-30 16:05:00"), Team1Id= 25,Team2Id= 28,HomeTeam=1}, 
                new Game {  GameFilterId = 4,GameDateTime= Convert.ToDateTime("2012-09-30 16:05:00"), Team1Id= 26,Team2Id= 8,HomeTeam=1}, 
                new Game {  GameFilterId = 4,GameDateTime= Convert.ToDateTime("2012-09-30 16:05:00"), Team1Id= 9,Team2Id= 30,HomeTeam=2 }, 
                new Game {  GameFilterId = 4,GameDateTime= Convert.ToDateTime("2012-09-30 16:25:00"), Team1Id= 33,Team2Id= 5,HomeTeam=1}, 
                new Game {  GameFilterId = 4,GameDateTime= Convert.ToDateTime("2012-09-30 16:25:00"), Team1Id= 27,Team2Id= 12,HomeTeam=1},
                new Game {  GameFilterId = 4,GameDateTime= Convert.ToDateTime("2012-09-30 16:30:00"), Team1Id= 7,Team2Id= 2,HomeTeam=1},
                new Game {  GameFilterId = 4,GameDateTime= Convert.ToDateTime("2012-10-01 20:35:00"), Team1Id= 11,Team2Id= 18,HomeTeam=1},
                new Game {  GameFilterId = 5,GameDateTime= Convert.ToDateTime("2012-10-04 20:25:00"), Team1Id= 25,Team2Id= 31,HomeTeam=2 },
                new Game {  GameFilterId = 5,GameDateTime= Convert.ToDateTime("2012-10-07 13:00:00"), Team1Id= 16,Team2Id= 12,HomeTeam=2 },
                new Game {  GameFilterId = 5,GameDateTime= Convert.ToDateTime("2012-10-07 13:00:00"), Team1Id= 13,Team2Id= 7,HomeTeam=1},
                new Game {  GameFilterId = 5,GameDateTime= Convert.ToDateTime("2012-10-07 13:00:00"), Team1Id= 33,Team2Id= 21,HomeTeam=2 }, 
                new Game {  GameFilterId = 5,GameDateTime= Convert.ToDateTime("2012-10-07 13:00:00"), Team1Id= 2,Team2Id= 29,HomeTeam=1}, 
                new Game {  GameFilterId = 5,GameDateTime= Convert.ToDateTime("2012-10-07 16:25:00"), Team1Id= 4,Team2Id= 32,HomeTeam=1},
                new Game {  GameFilterId = 5,GameDateTime= Convert.ToDateTime("2012-10-07 13:00:00"), Team1Id= 9,Team2Id= 28,HomeTeam=1},
                new Game {  GameFilterId = 5,GameDateTime= Convert.ToDateTime("2012-10-07 13:00:00"), Team1Id= 22,Team2Id= 23,HomeTeam=2 }, 
                new Game {  GameFilterId = 5,GameDateTime= Convert.ToDateTime("2012-10-07 16:05:00"), Team1Id= 17,Team2Id= 24,HomeTeam=1}, 
                new Game {  GameFilterId = 5,GameDateTime= Convert.ToDateTime("2012-10-07 16:05:00"), Team1Id= 18,Team2Id= 30,HomeTeam=2 }, 
                new Game {  GameFilterId = 5,GameDateTime= Convert.ToDateTime("2012-10-07 16:25:00"), Team1Id= 3,Team2Id= 26,HomeTeam=1},
                new Game {  GameFilterId = 5,GameDateTime= Convert.ToDateTime("2012-10-07 16:25:00"), Team1Id= 15,Team2Id= 6,HomeTeam=1}, 
                new Game {  GameFilterId = 5,GameDateTime= Convert.ToDateTime("2012-10-07 20:30:00"), Team1Id= 5,Team2Id= 14,HomeTeam=1}, 
                new Game {  GameFilterId = 5,GameDateTime= Convert.ToDateTime("2012-10-08 20:35:00"), Team1Id= 10,Team2Id= 20,HomeTeam=2 }, 
                new Game {  GameFilterId = 6,GameDateTime= Convert.ToDateTime("2012-10-11 20:25:00"), Team1Id= 13,Team2Id= 32,HomeTeam=2 }, 
                new Game {  GameFilterId = 6,GameDateTime= Convert.ToDateTime("2012-10-14 13:00:00"), Team1Id= 9,Team2Id= 29,HomeTeam=2 },
                new Game {  GameFilterId = 6,GameDateTime= Convert.ToDateTime("2012-10-14 13:00:00"), Team1Id= 20,Team2Id= 21,HomeTeam=1},
                new Game {  GameFilterId = 6,GameDateTime= Convert.ToDateTime("2012-10-14 13:00:00"), Team1Id= 27,Team2Id= 23,HomeTeam=1},
                new Game {  GameFilterId = 6,GameDateTime= Convert.ToDateTime("2012-10-14 13:00:00"), Team1Id= 16,Team2Id= 8,HomeTeam=1}, 
                new Game {  GameFilterId = 6,GameDateTime= Convert.ToDateTime("2012-10-14 13:00:00"), Team1Id= 22,Team2Id= 11,HomeTeam=1},
                new Game {  GameFilterId = 6,GameDateTime= Convert.ToDateTime("2012-10-14 13:00:00"), Team1Id= 7,Team2Id= 19,HomeTeam=1}, 
                new Game {  GameFilterId = 6,GameDateTime= Convert.ToDateTime("2012-10-14 13:00:00"), Team1Id= 28,Team2Id= 31,HomeTeam=1}, 
                new Game {  GameFilterId = 6,GameDateTime= Convert.ToDateTime("2012-10-14 16:05:00"), Team1Id= 3,Team2Id= 24,HomeTeam=2 }, 
                new Game {  GameFilterId = 6,GameDateTime= Convert.ToDateTime("2012-10-14 16:05:00"), Team1Id= 25,Team2Id= 6,HomeTeam=1}, 
                new Game {  GameFilterId = 6,GameDateTime= Convert.ToDateTime("2012-10-14 16:25:00"), Team1Id= 12,Team2Id= 4,HomeTeam=1}, 
                new Game {  GameFilterId = 6,GameDateTime= Convert.ToDateTime("2012-10-14 16:25:00"), Team1Id= 15,Team2Id= 2,HomeTeam=1},
                new Game {  GameFilterId = 6,GameDateTime= Convert.ToDateTime("2012-10-14 20:30:00"), Team1Id= 10,Team2Id= 33,HomeTeam=1},
                new Game {  GameFilterId = 6,GameDateTime= Convert.ToDateTime("2012-10-15 20:40:00"), Team1Id= 14,Team2Id= 26,HomeTeam=1}
            };

            return games;
        }

        public List<GameSpread> InitializeGameSpreads()
        {
            var gameSpreads = new List<GameSpread>
            {
                new GameSpread {  GameId = 1, FavoriteTeamId= 33,UnderdogTeamId= 18,Spread=  Convert.ToDecimal(6)}, 
                new GameSpread {  GameId = 2, FavoriteTeamId= 2,UnderdogTeamId= 27,Spread=  Convert.ToDecimal(7.5)}, 
                new GameSpread {  GameId = 3, FavoriteTeamId= 3,UnderdogTeamId= 25,Spread=  Convert.ToDecimal(13.5)}, 
                new GameSpread {  GameId = 4, FavoriteTeamId= 4,UnderdogTeamId= 21,Spread=  Convert.ToDecimal(1.5) }, 
                new GameSpread {  GameId = 5, FavoriteTeamId= 5,UnderdogTeamId= 17,Spread=  Convert.ToDecimal(2.5) }, 
                new GameSpread {  GameId = 6, FavoriteTeamId= 6,UnderdogTeamId= 23,Spread=  Convert.ToDecimal(3)}, 
                new GameSpread {  GameId = 7, FavoriteTeamId= 7,UnderdogTeamId= 22,Spread=  Convert.ToDecimal(2.5)}, 
                new GameSpread {  GameId = 8, FavoriteTeamId= 8,UnderdogTeamId= 28,Spread=  Convert.ToDecimal(2.5) }, 
                new GameSpread {  GameId = 9, FavoriteTeamId= 9,UnderdogTeamId= 29,Spread=  Convert.ToDecimal(7)},
                new GameSpread {  GameId = 10, FavoriteTeamId= 10,UnderdogTeamId= 30,Spread=  Convert.ToDecimal(7.5) }, 
                new GameSpread {  GameId = 11, FavoriteTeamId= 11,UnderdogTeamId= 24,Spread=  Convert.ToDecimal(3) },
                new GameSpread {  GameId = 12, FavoriteTeamId= 12,UnderdogTeamId= 31,Spread=  Convert.ToDecimal(3) }, 
                new GameSpread {  GameId = 13, FavoriteTeamId= 13,UnderdogTeamId= 20,Spread=  Convert.ToDecimal(6)}, 
                new GameSpread {  GameId = 14, FavoriteTeamId= 14,UnderdogTeamId= 32,Spread=  Convert.ToDecimal(6)}, 
                new GameSpread {  GameId = 15, FavoriteTeamId= 15,UnderdogTeamId= 19,Spread=  Convert.ToDecimal(6.5)},
                new GameSpread {  GameId = 16, FavoriteTeamId= 16,UnderdogTeamId= 26,Spread=  Convert.ToDecimal(3)}, 
                new GameSpread {  GameId = 17, FavoriteTeamId= 17,UnderdogTeamId= 2,Spread=  Convert.ToDecimal(2.5)}, 
                new GameSpread {  GameId = 18, FavoriteTeamId= 18,UnderdogTeamId= 31,Spread=  Convert.ToDecimal(7.5)},
                new GameSpread {  GameId = 19, FavoriteTeamId= 11,UnderdogTeamId= 27,Spread=  Convert.ToDecimal(8)}, 
                new GameSpread {  GameId = 20, FavoriteTeamId= 15,UnderdogTeamId= 4,Spread=  Convert.ToDecimal(6.5) }, 
                new GameSpread {  GameId = 21, FavoriteTeamId= 19,UnderdogTeamId= 32,Spread=  Convert.ToDecimal(3.5) }, 
                new GameSpread {  GameId = 22, FavoriteTeamId= 12,UnderdogTeamId= 9,Spread=  Convert.ToDecimal(3)}, 
                new GameSpread {  GameId = 23, FavoriteTeamId= 20,UnderdogTeamId= 28,Spread=  Convert.ToDecimal(2.5) }, 
                new GameSpread {  GameId = 24, FavoriteTeamId= 5,UnderdogTeamId= 23,Spread=  Convert.ToDecimal(9)}, 
                new GameSpread {  GameId = 25, FavoriteTeamId= 6,UnderdogTeamId= 29,Spread=  Convert.ToDecimal(3) }, 
                new GameSpread {  GameId = 26, FavoriteTeamId= 21,UnderdogTeamId= 30,Spread=  Convert.ToDecimal(3)},
                new GameSpread {  GameId = 27, FavoriteTeamId= 7,UnderdogTeamId= 25,Spread=  Convert.ToDecimal(3.5) },
                new GameSpread {  GameId = 28, FavoriteTeamId= 14,UnderdogTeamId= 16,Spread=  Convert.ToDecimal(3)}, 
                new GameSpread {  GameId = 29, FavoriteTeamId= 10,UnderdogTeamId= 26,Spread=  Convert.ToDecimal(2) }, 
                new GameSpread {  GameId = 30, FavoriteTeamId= 13,UnderdogTeamId= 8,Spread=  Convert.ToDecimal(4.5) },
                new GameSpread {  GameId = 31, FavoriteTeamId= 22,UnderdogTeamId= 3,Spread=  Convert.ToDecimal(3)}, 
                new GameSpread {  GameId = 32, FavoriteTeamId= 33,UnderdogTeamId= 24,Spread=  Convert.ToDecimal(3) },
                new GameSpread {  GameId = 33, FavoriteTeamId= 22,UnderdogTeamId= 29,Spread=  Convert.ToDecimal(13)},
                new GameSpread {  GameId = 34, FavoriteTeamId= 3,UnderdogTeamId= 6,Spread=  Convert.ToDecimal(4) }, 
                new GameSpread {  GameId = 35, FavoriteTeamId= 19,UnderdogTeamId= 4,Spread=  Convert.ToDecimal(4)}, 
                new GameSpread {  GameId = 36, FavoriteTeamId= 16,UnderdogTeamId= 17,Spread=  Convert.ToDecimal(7)},
                new GameSpread {  GameId = 37, FavoriteTeamId= 15,UnderdogTeamId= 20,Spread=  Convert.ToDecimal(4) },
                new GameSpread {  GameId = 38, FavoriteTeamId= 23,UnderdogTeamId= 14,Spread=  Convert.ToDecimal(1)},
                new GameSpread {  GameId = 39, FavoriteTeamId= 10,UnderdogTeamId= 32,Spread=  Convert.ToDecimal(12)}, 
                new GameSpread {  GameId = 40, FavoriteTeamId= 24,UnderdogTeamId= 31,Spread=  Convert.ToDecimal(2.5) },
                new GameSpread {  GameId = 41, FavoriteTeamId= 25,UnderdogTeamId= 28,Spread=  Convert.ToDecimal(6.5)}, 
                new GameSpread {  GameId = 42, FavoriteTeamId= 26,UnderdogTeamId= 8,Spread=  Convert.ToDecimal(6.5)}, 
                new GameSpread {  GameId = 43, FavoriteTeamId= 9,UnderdogTeamId= 30,Spread=  Convert.ToDecimal(2) }, 
                new GameSpread {  GameId = 44, FavoriteTeamId= 33,UnderdogTeamId= 5,Spread=  Convert.ToDecimal(8)}, 
                new GameSpread {  GameId = 45, FavoriteTeamId= 27,UnderdogTeamId= 12,Spread=  Convert.ToDecimal(3)},
                new GameSpread {  GameId = 46, FavoriteTeamId= 7,UnderdogTeamId= 2,Spread=  Convert.ToDecimal(2)},
                new GameSpread {  GameId = 47, FavoriteTeamId= 11,UnderdogTeamId= 18,Spread=  Convert.ToDecimal(4)},
                new GameSpread {  GameId = 48, FavoriteTeamId= 25,UnderdogTeamId= 31,Spread=  Convert.ToDecimal(1.5) },
                new GameSpread {  GameId = 49, FavoriteTeamId= 16,UnderdogTeamId= 12,Spread=  Convert.ToDecimal(3) },
                new GameSpread {  GameId = 50, FavoriteTeamId= 13,UnderdogTeamId= 7,Spread=  Convert.ToDecimal(3.5)},
                new GameSpread {  GameId = 51, FavoriteTeamId= 33,UnderdogTeamId= 21,Spread=  Convert.ToDecimal(7) }, 
                new GameSpread {  GameId = 52, FavoriteTeamId= 2,UnderdogTeamId= 29,Spread=  Convert.ToDecimal(9)}, 
                new GameSpread {  GameId = 53, FavoriteTeamId= 4,UnderdogTeamId= 32,Spread=  Convert.ToDecimal(5.5)},
                new GameSpread {  GameId = 54, FavoriteTeamId= 9,UnderdogTeamId= 28,Spread=  Convert.ToDecimal(3.5)},
                new GameSpread {  GameId = 55,FavoriteTeamId= 22,UnderdogTeamId= 23,Spread=  Convert.ToDecimal(6) }, 
                new GameSpread {  GameId = 56, FavoriteTeamId= 17,UnderdogTeamId= 24,Spread=  Convert.ToDecimal(3)}, 
                new GameSpread {  GameId = 57,FavoriteTeamId= 18,UnderdogTeamId= 30,Spread=  Convert.ToDecimal(6) }, 
                new GameSpread {  GameId = 58, FavoriteTeamId= 3,UnderdogTeamId= 26,Spread=  Convert.ToDecimal(6.5)},
                new GameSpread {  GameId = 59, FavoriteTeamId= 15,UnderdogTeamId= 6,Spread=  Convert.ToDecimal(9.5)}, 
                new GameSpread {  GameId = 60, FavoriteTeamId= 5,UnderdogTeamId= 14,Spread=  Convert.ToDecimal(3.5)}, 
                new GameSpread {  GameId = 61, FavoriteTeamId= 10,UnderdogTeamId= 20,Spread=  Convert.ToDecimal(8) }, 
                new GameSpread {  GameId = 62, FavoriteTeamId= 13,UnderdogTeamId= 32,Spread=  Convert.ToDecimal(6) }, 
                new GameSpread {  GameId = 63, FavoriteTeamId= 9,UnderdogTeamId= 29,Spread=  Convert.ToDecimal(1) },
                new GameSpread {  GameId = 64, FavoriteTeamId= 20,UnderdogTeamId= 21,Spread=  Convert.ToDecimal(3)},
                new GameSpread {  GameId = 65, FavoriteTeamId= 27,UnderdogTeamId= 23,Spread=  Convert.ToDecimal(4)},
                new GameSpread {  GameId = 66, FavoriteTeamId= 16,UnderdogTeamId= 8,Spread=  Convert.ToDecimal(9)}, 
                new GameSpread {  GameId = 67,FavoriteTeamId= 22,UnderdogTeamId= 11,Spread=  Convert.ToDecimal(3.5)},
                new GameSpread {  GameId = 68, FavoriteTeamId= 7,UnderdogTeamId= 19,Spread=  Convert.ToDecimal(4)}, 
                new GameSpread {  GameId = 69, FavoriteTeamId= 28,UnderdogTeamId= 31,Spread=  Convert.ToDecimal(3.5)}, 
                new GameSpread {  GameId = 70,FavoriteTeamId= 3,UnderdogTeamId= 24,Spread=  Convert.ToDecimal(3.5) }, 
                new GameSpread {  GameId = 71, FavoriteTeamId= 25,UnderdogTeamId= 6,Spread=  Convert.ToDecimal(4.5)}, 
                new GameSpread {  GameId = 72, FavoriteTeamId= 12,UnderdogTeamId= 4,Spread=  Convert.ToDecimal(2)}, 
                new GameSpread {  GameId = 73, FavoriteTeamId= 15,UnderdogTeamId= 2,Spread=  Convert.ToDecimal(6.5)},
                new GameSpread {  GameId = 74, FavoriteTeamId= 10,UnderdogTeamId= 33,Spread=  Convert.ToDecimal(3.5)},
                new GameSpread {  GameId = 75,FavoriteTeamId= 14,UnderdogTeamId= 26,Spread=  Convert.ToDecimal(1)}
            };

            return gameSpreads;
        }


        public List<GameResult> InitializeGameResults()
        {
            var gameResults = new List<GameResult>
            {
                new GameResult {  GameSpreadId = 1, WinnerTeamId=1, FavoriteScore= 33,UnderdogScore= 18, GamePeriod="F"},
                new GameResult {  GameSpreadId = 2, WinnerTeamId=1, FavoriteScore= 2,UnderdogScore= 27, GamePeriod="F"},
                new GameResult {  GameSpreadId = 3, WinnerTeamId=1, FavoriteScore= 3,UnderdogScore= 25, GamePeriod="F"}, 
                new GameResult {  GameSpreadId = 4, WinnerTeamId=1, FavoriteScore= 4,UnderdogScore= 21, GamePeriod="F"}, 
                new GameResult {  GameSpreadId = 5, WinnerTeamId=1, FavoriteScore= 5,UnderdogScore= 17, GamePeriod="F"}, 
                new GameResult {  GameSpreadId = 6, WinnerTeamId=1, FavoriteScore= 6,UnderdogScore= 23, GamePeriod="F"},
                new GameResult {  GameSpreadId = 7, WinnerTeamId=1, FavoriteScore= 7,UnderdogScore= 22, GamePeriod="F"},
                new GameResult {  GameSpreadId = 8, WinnerTeamId=1, FavoriteScore= 8,UnderdogScore= 28, GamePeriod="F"}, 
                new GameResult {  GameSpreadId = 9, WinnerTeamId=1, FavoriteScore= 9,UnderdogScore= 29, GamePeriod="F"},
                new GameResult {  GameSpreadId = 10, WinnerTeamId=1, FavoriteScore= 10,UnderdogScore= 30, GamePeriod="F"}, 
                new GameResult {  GameSpreadId = 11, WinnerTeamId=1, FavoriteScore= 11,UnderdogScore= 24, GamePeriod="F"},
                new GameResult {  GameSpreadId = 12, WinnerTeamId=1, FavoriteScore= 12,UnderdogScore= 31, GamePeriod="F"},
                new GameResult {  GameSpreadId = 13, WinnerTeamId=1, FavoriteScore= 13,UnderdogScore= 20, GamePeriod="F"},
                new GameResult {  GameSpreadId = 14, WinnerTeamId=1, FavoriteScore= 14,UnderdogScore= 32, GamePeriod="F"},
                new GameResult {  GameSpreadId = 15, WinnerTeamId=1, FavoriteScore= 15,UnderdogScore= 19, GamePeriod="F"},
                new GameResult {  GameSpreadId = 16, WinnerTeamId=1, FavoriteScore= 16,UnderdogScore= 26, GamePeriod="F"},
                new GameResult {  GameSpreadId = 17, WinnerTeamId=1, FavoriteScore= 17,UnderdogScore= 2, GamePeriod="F"},
                new GameResult {  GameSpreadId = 18, WinnerTeamId=1, FavoriteScore= 18,UnderdogScore= 31, GamePeriod="F"},
                new GameResult {  GameSpreadId = 19, WinnerTeamId=1, FavoriteScore= 11,UnderdogScore= 27, GamePeriod="F"},
                new GameResult {  GameSpreadId = 20, WinnerTeamId=1, FavoriteScore= 15,UnderdogScore= 4, GamePeriod="F"}, 
                new GameResult {  GameSpreadId = 21, WinnerTeamId=1, FavoriteScore= 19,UnderdogScore= 32, GamePeriod="F"}, 
                new GameResult {  GameSpreadId = 22, WinnerTeamId=1, FavoriteScore= 12,UnderdogScore= 9, GamePeriod="F"},
                new GameResult {  GameSpreadId = 23, WinnerTeamId=1, FavoriteScore= 20,UnderdogScore= 28, GamePeriod="F"}, 
                new GameResult {  GameSpreadId = 24, WinnerTeamId=1, FavoriteScore= 5,UnderdogScore= 23, GamePeriod="F"},
                new GameResult {  GameSpreadId = 25, WinnerTeamId=1, FavoriteScore= 6,UnderdogScore= 29, GamePeriod="F"},
                new GameResult {  GameSpreadId = 26, WinnerTeamId=1, FavoriteScore= 21,UnderdogScore= 30, GamePeriod="F"},
                new GameResult {  GameSpreadId = 27, WinnerTeamId=1, FavoriteScore= 7,UnderdogScore= 25, GamePeriod="F"},
                new GameResult {  GameSpreadId = 28, WinnerTeamId=1, FavoriteScore= 14,UnderdogScore= 16, GamePeriod="F"},
                new GameResult {  GameSpreadId = 29, WinnerTeamId=1, FavoriteScore= 10,UnderdogScore= 26, GamePeriod="F"},
                new GameResult {  GameSpreadId = 30, WinnerTeamId=1, FavoriteScore= 13,UnderdogScore= 8, GamePeriod="F"},
                new GameResult {  GameSpreadId = 31, WinnerTeamId=1, FavoriteScore= 22,UnderdogScore= 3, GamePeriod="F"},
                new GameResult {  GameSpreadId = 32, WinnerTeamId=1, FavoriteScore= 33,UnderdogScore= 24, GamePeriod="F"},
                new GameResult {  GameSpreadId = 33, WinnerTeamId=1, FavoriteScore= 22,UnderdogScore= 29, GamePeriod="F"},
                new GameResult {  GameSpreadId = 34, WinnerTeamId=1, FavoriteScore= 3,UnderdogScore= 6, GamePeriod="F"},
                new GameResult {  GameSpreadId = 35, WinnerTeamId=1, FavoriteScore= 19,UnderdogScore= 4, GamePeriod="F"},
                new GameResult {  GameSpreadId = 36, WinnerTeamId=1, FavoriteScore= 16,UnderdogScore= 17, GamePeriod="F"},
                new GameResult {  GameSpreadId = 37, WinnerTeamId=1, FavoriteScore= 15,UnderdogScore= 20, GamePeriod="F"},
                new GameResult {  GameSpreadId = 38, WinnerTeamId=1, FavoriteScore= 23,UnderdogScore= 14, GamePeriod="F"},
                new GameResult {  GameSpreadId = 39, WinnerTeamId=1, FavoriteScore= 10,UnderdogScore= 32, GamePeriod="F"},
                new GameResult {  GameSpreadId = 40, WinnerTeamId=1, FavoriteScore= 24,UnderdogScore= 31, GamePeriod="F"},
                new GameResult {  GameSpreadId = 41, WinnerTeamId=1, FavoriteScore= 25,UnderdogScore= 28, GamePeriod="F"},
                new GameResult {  GameSpreadId = 42, WinnerTeamId=1, FavoriteScore= 26,UnderdogScore= 8, GamePeriod="F"},
                new GameResult {  GameSpreadId = 43, WinnerTeamId=1, FavoriteScore= 9,UnderdogScore= 30, GamePeriod="F"},
                new GameResult {  GameSpreadId = 44, WinnerTeamId=1, FavoriteScore= 33,UnderdogScore= 5, GamePeriod="F"},
                new GameResult {  GameSpreadId = 45, WinnerTeamId=1, FavoriteScore= 27,UnderdogScore= 12, GamePeriod="F"},
                new GameResult {  GameSpreadId = 46, WinnerTeamId=1, FavoriteScore= 7,UnderdogScore= 2, GamePeriod="F"},
                new GameResult {  GameSpreadId = 47, WinnerTeamId=1, FavoriteScore= 11,UnderdogScore= 18, GamePeriod="F"},
                new GameResult {  GameSpreadId = 48, WinnerTeamId=1, FavoriteScore= 25,UnderdogScore= 31, GamePeriod="F"},
                new GameResult {  GameSpreadId = 49, WinnerTeamId=1, FavoriteScore= 16,UnderdogScore= 12, GamePeriod="F"},
                new GameResult {  GameSpreadId = 50, WinnerTeamId=1, FavoriteScore= 13,UnderdogScore= 7, GamePeriod="F"},
                new GameResult {  GameSpreadId = 51, WinnerTeamId=1, FavoriteScore= 33,UnderdogScore= 21, GamePeriod="F"},
                new GameResult {  GameSpreadId = 52, WinnerTeamId=1, FavoriteScore= 2,UnderdogScore= 29, GamePeriod="F"},
                new GameResult {  GameSpreadId = 53, WinnerTeamId=1, FavoriteScore= 4,UnderdogScore= 32, GamePeriod="F"},
                new GameResult {  GameSpreadId = 54, WinnerTeamId=1, FavoriteScore= 9,UnderdogScore= 28, GamePeriod="F"},
                new GameResult {  GameSpreadId = 55, WinnerTeamId=1, FavoriteScore= 22,UnderdogScore= 23, GamePeriod="F"},
                new GameResult {  GameSpreadId = 56, WinnerTeamId=1, FavoriteScore= 17,UnderdogScore= 24, GamePeriod="F"},
                new GameResult {  GameSpreadId = 57, WinnerTeamId=1, FavoriteScore= 18,UnderdogScore= 30, GamePeriod="F"},
                new GameResult {  GameSpreadId = 58, WinnerTeamId=1, FavoriteScore= 3,UnderdogScore= 26, GamePeriod="F"},
                new GameResult {  GameSpreadId = 59, WinnerTeamId=1, FavoriteScore= 15,UnderdogScore= 6, GamePeriod="F"},
                new GameResult {  GameSpreadId = 60, WinnerTeamId=1, FavoriteScore= 5,UnderdogScore= 14, GamePeriod="F"},
                new GameResult {  GameSpreadId = 61, WinnerTeamId=1, FavoriteScore= 10,UnderdogScore= 20, GamePeriod="F"},
                new GameResult {  GameSpreadId = 62, WinnerTeamId=1, FavoriteScore= 13,UnderdogScore= 32, GamePeriod="F"},
                new GameResult {  GameSpreadId = 63, WinnerTeamId=1, FavoriteScore= 9,UnderdogScore= 29, GamePeriod="F"},
                new GameResult {  GameSpreadId = 64, WinnerTeamId=1, FavoriteScore= 20,UnderdogScore= 21, GamePeriod="F"},
                new GameResult {  GameSpreadId = 65, WinnerTeamId=1, FavoriteScore= 27,UnderdogScore= 23, GamePeriod="F"},
                new GameResult {  GameSpreadId = 66, WinnerTeamId=1, FavoriteScore= 16,UnderdogScore= 8, GamePeriod="F"},
                new GameResult {  GameSpreadId = 67, WinnerTeamId=1, FavoriteScore= 22,UnderdogScore= 11, GamePeriod="F"},
                new GameResult {  GameSpreadId = 68, WinnerTeamId=1, FavoriteScore= 7,UnderdogScore= 19, GamePeriod="F"},
                new GameResult {  GameSpreadId = 69, WinnerTeamId=1, FavoriteScore= 28,UnderdogScore= 31, GamePeriod="F"},
                new GameResult {  GameSpreadId = 70, WinnerTeamId=1, FavoriteScore= 3,UnderdogScore= 24, GamePeriod="F"}, 
                new GameResult {  GameSpreadId = 71, WinnerTeamId=1, FavoriteScore= 25,UnderdogScore= 6, GamePeriod="F"},
                new GameResult {  GameSpreadId = 72, WinnerTeamId=1, FavoriteScore= 12,UnderdogScore= 4, GamePeriod="F"},
                new GameResult {  GameSpreadId = 73, WinnerTeamId=1, FavoriteScore= 15,UnderdogScore= 2, GamePeriod="F"},
                new GameResult {  GameSpreadId = 74, WinnerTeamId=1, FavoriteScore= 10,UnderdogScore= 33, GamePeriod="F"},
                new GameResult {  GameSpreadId = 75, WinnerTeamId=1, FavoriteScore= 14,UnderdogScore= 26, GamePeriod="F"}
            };

            return gameResults;
        }

        public List<UserGameSelection> InitializeUserGameSelections()
        {
            var userGameSelections = new List<UserGameSelection>
            {
                new UserGameSelection {UserId= 1,GameSpreadId= 1,Bet= 1,PickTeamId= 33}, 
                new UserGameSelection {UserId= 1,GameSpreadId= 2,Bet= 1,PickTeamId= 2}, 
                new UserGameSelection {UserId= 1,GameSpreadId= 3,Bet= 4,PickTeamId= 3}, 
                new UserGameSelection {UserId= 1,GameSpreadId= 4,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 1,GameSpreadId= 5,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 1,GameSpreadId= 6,Bet= 1,PickTeamId= 23}, 
                new UserGameSelection {UserId= 1,GameSpreadId= 7,Bet= 1,PickTeamId= 22}, 
                new UserGameSelection {UserId= 1,GameSpreadId= 8,Bet= 1,PickTeamId= 8}, 
                new UserGameSelection {UserId= 1,GameSpreadId= 9,Bet= 1,PickTeamId= 9}, 
                new UserGameSelection {UserId= 1,GameSpreadId= 10,Bet= 1,PickTeamId= 10}, 
                new UserGameSelection {UserId= 1,GameSpreadId= 11,Bet= 1,PickTeamId= 11},
                new UserGameSelection {UserId= 1,GameSpreadId= 12,Bet= 1,PickTeamId= 12}, 
                new UserGameSelection {UserId= 1,GameSpreadId= 13,Bet= 1,PickTeamId= 20}, 
                new UserGameSelection {UserId= 1,GameSpreadId= 14,Bet= 1,PickTeamId= 14}, 
                new UserGameSelection {UserId= 1,GameSpreadId= 15,Bet= 3,PickTeamId= 19}, 
                new UserGameSelection {UserId= 1,GameSpreadId= 16,Bet= 1,PickTeamId= 16}, 
                new UserGameSelection {UserId= 2,GameSpreadId= 1,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 2,GameSpreadId= 2,Bet= 1,PickTeamId= 2},
                new UserGameSelection {UserId= 2,GameSpreadId= 3,Bet= 5,PickTeamId= 3},
                new UserGameSelection {UserId= 2,GameSpreadId= 4,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 2,GameSpreadId= 5,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 2,GameSpreadId= 6,Bet= 0,PickTeamId= 1},
                new UserGameSelection {UserId= 2,GameSpreadId= 7,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 2,GameSpreadId= 8,Bet= 1,PickTeamId= 8}, 
                new UserGameSelection {UserId= 2,GameSpreadId= 9,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 2,GameSpreadId= 10,Bet= 2,PickTeamId= 10}, 
                new UserGameSelection {UserId= 2,GameSpreadId= 11,Bet= 1,PickTeamId= 11}, 
                new UserGameSelection {UserId= 2,GameSpreadId= 12,Bet= 1,PickTeamId= 12}, 
                new UserGameSelection {UserId= 2,GameSpreadId= 13,Bet= 0,PickTeamId= 1},
                new UserGameSelection {UserId= 2,GameSpreadId= 14,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 2,GameSpreadId= 15,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 2,GameSpreadId= 16,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 3,GameSpreadId= 1,Bet= 1,PickTeamId= 33}, 
                new UserGameSelection {UserId= 3,GameSpreadId= 2,Bet= 1,PickTeamId= 2},
                new UserGameSelection {UserId= 3,GameSpreadId= 3,Bet= 4,PickTeamId= 3},
                new UserGameSelection {UserId= 3,GameSpreadId= 4,Bet= 1,PickTeamId= 21},
                new UserGameSelection {UserId= 3,GameSpreadId= 5,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 3,GameSpreadId= 6,Bet= 0,PickTeamId= 1},
                new UserGameSelection {UserId= 3,GameSpreadId= 7,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 3,GameSpreadId= 8,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 3,GameSpreadId= 9,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 3,GameSpreadId= 10,Bet= 0,PickTeamId= 1},
                new UserGameSelection {UserId= 3,GameSpreadId= 11,Bet= 0,PickTeamId= 1},
                new UserGameSelection {UserId= 3,GameSpreadId= 12,Bet= 0,PickTeamId= 1},
                new UserGameSelection {UserId= 3,GameSpreadId= 13,Bet= 1,PickTeamId= 13},
                new UserGameSelection {UserId= 3,GameSpreadId= 14,Bet= 1,PickTeamId= 14},
                new UserGameSelection {UserId= 3,GameSpreadId= 15,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 3,GameSpreadId= 16,Bet= 2,PickTeamId= 26},
                new UserGameSelection {UserId= 4,GameSpreadId= 1,Bet= 3,PickTeamId= 33}, 
                new UserGameSelection {UserId= 4,GameSpreadId= 2,Bet= 1,PickTeamId= 2}, 
                new UserGameSelection {UserId= 4,GameSpreadId= 3,Bet= 3,PickTeamId= 3}, 
                new UserGameSelection {UserId= 4,GameSpreadId= 4,Bet= 0,PickTeamId= 1},
                new UserGameSelection {UserId= 4,GameSpreadId= 5,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 4,GameSpreadId= 6,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 4,GameSpreadId= 7,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 4,GameSpreadId= 8,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 4,GameSpreadId= 9,Bet= 1,PickTeamId= 9}, 
                new UserGameSelection {UserId= 4,GameSpreadId= 10,Bet= 1,PickTeamId= 10},
                new UserGameSelection {UserId= 4,GameSpreadId= 11,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 4,GameSpreadId= 12,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 4,GameSpreadId= 13,Bet= 1,PickTeamId= 13},
                new UserGameSelection {UserId= 4,GameSpreadId= 14,Bet= 1,PickTeamId= 14},
                new UserGameSelection {UserId= 4,GameSpreadId= 15,Bet= 2,PickTeamId= 15}, 
                new UserGameSelection {UserId= 4,GameSpreadId= 16,Bet= 0,PickTeamId= 1},
                new UserGameSelection {UserId= 1,GameSpreadId= 17,Bet= 1,PickTeamId= 2}, 
                new UserGameSelection {UserId= 1,GameSpreadId= 18,Bet= 5,PickTeamId= 18},
                new UserGameSelection {UserId= 1,GameSpreadId= 19,Bet= 1,PickTeamId= 11},
                new UserGameSelection {UserId= 1,GameSpreadId= 20,Bet= 4,PickTeamId= 15},
                new UserGameSelection {UserId= 1,GameSpreadId= 21,Bet= 1,PickTeamId= 19},
                new UserGameSelection {UserId= 1,GameSpreadId= 22,Bet= 1,PickTeamId= 12}, 
                new UserGameSelection {UserId= 1,GameSpreadId= 23,Bet= 1,PickTeamId= 20}, 
                new UserGameSelection {UserId= 1,GameSpreadId= 24,Bet= 1,PickTeamId= 5}, 
                new UserGameSelection {UserId= 1,GameSpreadId= 25,Bet= 1,PickTeamId= 29},
                new UserGameSelection {UserId= 1,GameSpreadId= 26,Bet= 1,PickTeamId= 21},
                new UserGameSelection {UserId= 1,GameSpreadId= 27,Bet= 2,PickTeamId= 25},
                new UserGameSelection {UserId= 1,GameSpreadId= 28,Bet= 2,PickTeamId= 16},
                new UserGameSelection {UserId= 1,GameSpreadId= 29,Bet= 2,PickTeamId= 26}, 
                new UserGameSelection {UserId= 1,GameSpreadId= 30,Bet= 1,PickTeamId= 13},
                new UserGameSelection {UserId= 1,GameSpreadId= 31,Bet= 1,PickTeamId= 3},
                new UserGameSelection {UserId= 1,GameSpreadId= 32,Bet= 1,PickTeamId= 33},
                new UserGameSelection {UserId= 2,GameSpreadId= 17,Bet= 1,PickTeamId= 17},
                new UserGameSelection {UserId= 2,GameSpreadId= 18,Bet= 4,PickTeamId= 18},
                new UserGameSelection {UserId= 2,GameSpreadId= 19,Bet= 1,PickTeamId= 11},
                new UserGameSelection {UserId= 2,GameSpreadId= 20,Bet= 4,PickTeamId= 15},
                new UserGameSelection {UserId= 2,GameSpreadId= 21,Bet= 1,PickTeamId= 19},
                new UserGameSelection {UserId= 2,GameSpreadId= 22,Bet= 1,PickTeamId= 12},
                new UserGameSelection {UserId= 2,GameSpreadId= 23,Bet= 1,PickTeamId= 20}, 
                new UserGameSelection {UserId= 2,GameSpreadId= 24,Bet= 2,PickTeamId= 5}, 
                new UserGameSelection {UserId= 2,GameSpreadId= 25,Bet= 1,PickTeamId= 6},
                 new UserGameSelection {UserId= 2,GameSpreadId= 26,Bet= 1,PickTeamId= 21},
                 new UserGameSelection {UserId= 2,GameSpreadId= 27,Bet= 1,PickTeamId= 7},
                 new UserGameSelection {UserId= 2,GameSpreadId= 28,Bet= 1,PickTeamId= 14},
                 new UserGameSelection {UserId= 2,GameSpreadId= 29,Bet= 1,PickTeamId= 10},
                 new UserGameSelection {UserId= 2,GameSpreadId= 30,Bet= 2,PickTeamId= 13},
                 new UserGameSelection {UserId= 2,GameSpreadId= 31,Bet= 1,PickTeamId= 22},
                 new UserGameSelection {UserId= 2,GameSpreadId= 32,Bet= 3,PickTeamId= 33},
                 new UserGameSelection {UserId= 3,GameSpreadId= 17,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameSpreadId= 18,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameSpreadId= 19,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameSpreadId= 20,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameSpreadId= 21,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameSpreadId= 22,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameSpreadId= 23,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameSpreadId= 24,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameSpreadId= 25,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameSpreadId= 26,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameSpreadId= 27,Bet= 1,PickTeamId= 7},
                 new UserGameSelection {UserId= 3,GameSpreadId= 28,Bet= 1,PickTeamId= 14},
                 new UserGameSelection {UserId= 3,GameSpreadId= 29,Bet= 1,PickTeamId= 26},
                 new UserGameSelection {UserId= 3,GameSpreadId= 30,Bet= 1,PickTeamId= 8},
                 new UserGameSelection {UserId= 3,GameSpreadId= 31,Bet= 1,PickTeamId= 22},
                 new UserGameSelection {UserId= 3,GameSpreadId= 32,Bet= 1,PickTeamId= 33},
                 new UserGameSelection {UserId= 4,GameSpreadId= 17,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameSpreadId= 18,Bet= 2,PickTeamId= 18},
                 new UserGameSelection {UserId= 4,GameSpreadId= 19,Bet= 1,PickTeamId= 11},
                 new UserGameSelection {UserId= 4,GameSpreadId= 20,Bet= 1,PickTeamId= 15},
                 new UserGameSelection {UserId= 4,GameSpreadId= 21,Bet= 1,PickTeamId= 19},
                 new UserGameSelection {UserId= 4,GameSpreadId= 22,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameSpreadId= 23,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameSpreadId= 24,Bet= 2,PickTeamId= 5},
                 new UserGameSelection {UserId= 4,GameSpreadId= 25,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameSpreadId= 26,Bet= 1,PickTeamId= 21},
                 new UserGameSelection {UserId= 4,GameSpreadId= 27,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameSpreadId= 28,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameSpreadId= 29,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameSpreadId= 30,Bet= 1,PickTeamId= 13},
                 new UserGameSelection {UserId= 4,GameSpreadId= 31,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameSpreadId= 32,Bet= 1,PickTeamId= 33},
                 new UserGameSelection {UserId= 1,GameSpreadId= 33,Bet= 5,PickTeamId= 22},
                 new UserGameSelection {UserId= 1,GameSpreadId= 34,Bet= 1,PickTeamId= 3},
                 new UserGameSelection {UserId= 1,GameSpreadId= 35,Bet= 1,PickTeamId= 19},
                 new UserGameSelection {UserId= 1,GameSpreadId= 36,Bet= 2,PickTeamId= 16},
                 new UserGameSelection {UserId= 1,GameSpreadId= 37,Bet= 1,PickTeamId= 20},
                 new UserGameSelection {UserId= 1,GameSpreadId= 38,Bet= 3,PickTeamId= 14},
                 new UserGameSelection {UserId= 1,GameSpreadId= 39,Bet= 1,PickTeamId= 10},
                 new UserGameSelection {UserId= 1,GameSpreadId= 40,Bet= 1,PickTeamId= 24},
                 new UserGameSelection {UserId= 1,GameSpreadId= 41,Bet= 1,PickTeamId= 25},
                 new UserGameSelection {UserId= 1,GameSpreadId= 42,Bet= 1,PickTeamId= 26},
                 new UserGameSelection {UserId= 1,GameSpreadId= 43,Bet= 3,PickTeamId= 30},
                 new UserGameSelection {UserId= 1,GameSpreadId= 44,Bet= 1,PickTeamId= 33},
                 new UserGameSelection {UserId= 1,GameSpreadId= 45,Bet= 1,PickTeamId= 27},
                 new UserGameSelection {UserId= 1,GameSpreadId= 46,Bet= 1,PickTeamId= 2},
                 new UserGameSelection {UserId= 1,GameSpreadId= 47,Bet= 1,PickTeamId= 11},
                 new UserGameSelection {UserId= 2,GameSpreadId= 33,Bet= 3,PickTeamId= 22},
                 new UserGameSelection {UserId= 2,GameSpreadId= 34,Bet= 1,PickTeamId= 3},
                 new UserGameSelection {UserId= 2,GameSpreadId= 35,Bet= 1,PickTeamId= 19},
                 new UserGameSelection {UserId= 2,GameSpreadId= 36,Bet= 3,PickTeamId= 16},
                 new UserGameSelection {UserId= 2,GameSpreadId= 37,Bet= 1,PickTeamId= 15},
                 new UserGameSelection {UserId= 2,GameSpreadId= 38,Bet= 1,PickTeamId= 14},
                 new UserGameSelection {UserId= 2,GameSpreadId= 39,Bet= 4,PickTeamId= 10},
                 new UserGameSelection {UserId= 2,GameSpreadId= 40,Bet= 1,PickTeamId= 24},
                 new UserGameSelection {UserId= 2,GameSpreadId= 41,Bet= 1,PickTeamId= 25},
                 new UserGameSelection {UserId= 2,GameSpreadId= 42,Bet= 1,PickTeamId= 26},
                 new UserGameSelection {UserId= 2,GameSpreadId= 43,Bet= 1,PickTeamId= 9},
                 new UserGameSelection {UserId= 2,GameSpreadId= 44,Bet= 1,PickTeamId= 33},
                 new UserGameSelection {UserId= 2,GameSpreadId= 45,Bet= 1,PickTeamId= 12},
                 new UserGameSelection {UserId= 2,GameSpreadId= 46,Bet= 2,PickTeamId= 2},
                 new UserGameSelection {UserId= 2,GameSpreadId= 47,Bet= 2,PickTeamId= 18},
                 new UserGameSelection {UserId= 3,GameSpreadId= 33,Bet= 4,PickTeamId= 22},
                 new UserGameSelection {UserId= 3,GameSpreadId= 34,Bet= 1,PickTeamId= 3},
                 new UserGameSelection {UserId= 3,GameSpreadId= 35,Bet= 1,PickTeamId= 19},
                 new UserGameSelection {UserId= 3,GameSpreadId= 36,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameSpreadId= 37,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameSpreadId= 38,Bet= 1,PickTeamId= 14},
                 new UserGameSelection {UserId= 3,GameSpreadId= 39,Bet= 1,PickTeamId= 10},
                 new UserGameSelection {UserId= 3,GameSpreadId= 40,Bet= 1,PickTeamId= 31},
                 new UserGameSelection {UserId= 3,GameSpreadId= 41,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameSpreadId= 42,Bet= 1,PickTeamId= 8},
                 new UserGameSelection {UserId= 3,GameSpreadId= 43,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameSpreadId= 44,Bet= 1,PickTeamId= 33},
                 new UserGameSelection {UserId= 3,GameSpreadId= 45,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameSpreadId= 46,Bet= 1,PickTeamId= 2},
                 new UserGameSelection {UserId= 3,GameSpreadId= 47,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameSpreadId= 33,Bet= 3,PickTeamId= 22},
                 new UserGameSelection {UserId= 4,GameSpreadId= 34,Bet= 1,PickTeamId= 3},
                 new UserGameSelection {UserId= 4,GameSpreadId= 35,Bet= 1,PickTeamId= 19},
                 new UserGameSelection {UserId= 4,GameSpreadId= 36,Bet= 1,PickTeamId= 16},
                 new UserGameSelection {UserId= 4,GameSpreadId= 37,Bet= 1,PickTeamId= 15},
                 new UserGameSelection {UserId= 4,GameSpreadId= 38,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameSpreadId= 39,Bet= 1,PickTeamId= 10},
                 new UserGameSelection {UserId= 4,GameSpreadId= 40,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameSpreadId= 41,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameSpreadId= 42,Bet= 1,PickTeamId= 26},
                 new UserGameSelection {UserId= 4,GameSpreadId= 43,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameSpreadId= 44,Bet= 1,PickTeamId= 33},
                 new UserGameSelection {UserId= 4,GameSpreadId= 45,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameSpreadId= 46,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameSpreadId= 47,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 1,GameSpreadId= 48,Bet= 1,PickTeamId= 25},
                 new UserGameSelection {UserId= 1,GameSpreadId= 49,Bet= 1,PickTeamId= 12},
                 new UserGameSelection {UserId= 1,GameSpreadId= 50,Bet= 1,PickTeamId= 13},
                 new UserGameSelection {UserId= 1,GameSpreadId= 51,Bet= 1,PickTeamId= 33},
                 new UserGameSelection {UserId= 1,GameSpreadId= 52,Bet= 5,PickTeamId= 2},
                 new UserGameSelection {UserId= 1,GameSpreadId= 53,Bet= 1,PickTeamId= 4},
                 new UserGameSelection {UserId= 1,GameSpreadId= 54,Bet= 1,PickTeamId= 9},
                 new UserGameSelection {UserId= 1,GameSpreadId= 55,Bet= 1,PickTeamId= 22},
                 new UserGameSelection {UserId= 1,GameSpreadId= 56,Bet= 1,PickTeamId= 17},
                 new UserGameSelection {UserId= 1,GameSpreadId= 57,Bet= 1,PickTeamId= 18},
                 new UserGameSelection {UserId= 1,GameSpreadId= 58,Bet= 1,PickTeamId= 3},
                 new UserGameSelection {UserId= 1,GameSpreadId= 59,Bet= 5,PickTeamId= 15},
                 new UserGameSelection {UserId= 1,GameSpreadId= 60,Bet= 1,PickTeamId= 14},
                 new UserGameSelection {UserId= 1,GameSpreadId= 61,Bet= 1,PickTeamId= 10},
                 new UserGameSelection {UserId= 2,GameSpreadId= 48,Bet= 1,PickTeamId= 25},
                 new UserGameSelection {UserId= 2,GameSpreadId= 49,Bet= 2,PickTeamId= 16},
                 new UserGameSelection {UserId= 2,GameSpreadId= 50,Bet= 1,PickTeamId= 13},
                 new UserGameSelection {UserId= 2,GameSpreadId= 51,Bet= 3,PickTeamId= 33},
                 new UserGameSelection {UserId= 2,GameSpreadId= 52,Bet= 2,PickTeamId= 2},
                 new UserGameSelection {UserId= 2,GameSpreadId= 53,Bet= 1,PickTeamId= 32},
                 new UserGameSelection {UserId= 2,GameSpreadId= 54,Bet= 1,PickTeamId= 28},
                 new UserGameSelection {UserId= 2,GameSpreadId= 55,Bet= 2,PickTeamId= 22},
                 new UserGameSelection {UserId= 2,GameSpreadId= 56,Bet= 1,PickTeamId= 17},
                 new UserGameSelection {UserId= 2,GameSpreadId= 57,Bet= 2,PickTeamId= 18},
                 new UserGameSelection {UserId= 2,GameSpreadId= 58,Bet= 1,PickTeamId= 3},
                 new UserGameSelection {UserId= 2,GameSpreadId= 59,Bet= 3,PickTeamId= 15},
                 new UserGameSelection {UserId= 2,GameSpreadId= 60,Bet= 1,PickTeamId= 5},
                 new UserGameSelection {UserId= 2,GameSpreadId= 61,Bet= 1,PickTeamId= 10},
                 new UserGameSelection {UserId= 3,GameSpreadId= 48,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameSpreadId= 49,Bet= 1,PickTeamId= 12},
                 new UserGameSelection {UserId= 3,GameSpreadId= 50,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameSpreadId= 51,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameSpreadId= 52,Bet= 1,PickTeamId= 2},
                 new UserGameSelection {UserId= 3,GameSpreadId= 53,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameSpreadId= 54,Bet= 1,PickTeamId= 28},
                 new UserGameSelection {UserId= 3,GameSpreadId= 55,Bet= 1,PickTeamId= 22},
                 new UserGameSelection {UserId= 3,GameSpreadId= 56,Bet= 1,PickTeamId= 24},
                 new UserGameSelection {UserId= 3,GameSpreadId= 57,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameSpreadId= 58,Bet= 1,PickTeamId= 26},
                 new UserGameSelection {UserId= 3,GameSpreadId= 59,Bet= 4,PickTeamId= 15},
                 new UserGameSelection {UserId= 3,GameSpreadId= 60,Bet= 1,PickTeamId= 14},
                 new UserGameSelection {UserId= 3,GameSpreadId= 61,Bet= 1,PickTeamId= 10},
                 new UserGameSelection {UserId= 4,GameSpreadId= 48,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameSpreadId= 49,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameSpreadId= 50,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameSpreadId= 51,Bet= 1,PickTeamId= 33},
                 new UserGameSelection {UserId= 4,GameSpreadId= 52,Bet= 1,PickTeamId= 2},
                 new UserGameSelection {UserId= 4,GameSpreadId= 53,Bet= 1,PickTeamId= 4},
                 new UserGameSelection {UserId= 4,GameSpreadId= 54,Bet= 1,PickTeamId= 9},
                 new UserGameSelection {UserId= 4,GameSpreadId= 55,Bet= 1,PickTeamId= 22},
                 new UserGameSelection {UserId= 4,GameSpreadId= 56,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameSpreadId= 57,Bet= 1,PickTeamId= 18},
                 new UserGameSelection {UserId= 4,GameSpreadId= 58,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameSpreadId= 59,Bet= 3,PickTeamId= 15},
                 new UserGameSelection {UserId= 4,GameSpreadId= 60,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameSpreadId= 61,Bet= 1,PickTeamId= 10},
                 new UserGameSelection {UserId= 1,GameSpreadId= 62,Bet= 1,PickTeamId= 13},
                 new UserGameSelection {UserId= 1,GameSpreadId= 63,Bet= 5,PickTeamId= 29},
                 new UserGameSelection {UserId= 1,GameSpreadId= 64,Bet= 1,PickTeamId= 20},
                 new UserGameSelection {UserId= 1,GameSpreadId= 65,Bet= 1,PickTeamId= 27},
                 new UserGameSelection {UserId= 1,GameSpreadId= 66,Bet= 5,PickTeamId= 16},
                 new UserGameSelection {UserId= 1,GameSpreadId= 67,Bet= 1,PickTeamId= 22},
                 new UserGameSelection {UserId= 1,GameSpreadId= 68,Bet= 1,PickTeamId= 19},
                 new UserGameSelection {UserId= 1,GameSpreadId= 69,Bet= 1,PickTeamId= 28},
                 new UserGameSelection {UserId= 1,GameSpreadId= 70,Bet= 1,PickTeamId= 24},
                 new UserGameSelection {UserId= 1,GameSpreadId= 71,Bet= 1,PickTeamId= 25},
                 new UserGameSelection {UserId= 1,GameSpreadId= 72,Bet= 1,PickTeamId= 4},
                 new UserGameSelection {UserId= 1,GameSpreadId= 73,Bet= 1,PickTeamId= 2},
                 new UserGameSelection {UserId= 1,GameSpreadId= 74,Bet= 1,PickTeamId= 10},
                 new UserGameSelection {UserId= 1,GameSpreadId= 75,Bet= 1,PickTeamId= 26},
                 new UserGameSelection {UserId= 2,GameSpreadId= 62,Bet= 2,PickTeamId= 13},
                 new UserGameSelection {UserId= 2,GameSpreadId= 63,Bet= 1,PickTeamId= 29},
                 new UserGameSelection {UserId= 2,GameSpreadId= 64,Bet= 1,PickTeamId= 20},
                 new UserGameSelection {UserId= 2,GameSpreadId= 65,Bet= 1,PickTeamId= 23},
                 new UserGameSelection {UserId= 2,GameSpreadId= 66,Bet= 3,PickTeamId= 16},
                 new UserGameSelection {UserId= 2,GameSpreadId= 67,Bet= 2,PickTeamId= 22},
                 new UserGameSelection {UserId= 2,GameSpreadId= 68,Bet= 1,PickTeamId= 7},
                 new UserGameSelection {UserId= 2,GameSpreadId= 69,Bet= 1,PickTeamId= 28},
                 new UserGameSelection {UserId= 2,GameSpreadId= 70,Bet= 3,PickTeamId= 3},
                 new UserGameSelection {UserId= 2,GameSpreadId= 71,Bet= 1,PickTeamId= 25},
                 new UserGameSelection {UserId= 2,GameSpreadId= 72,Bet= 1,PickTeamId= 4},
                 new UserGameSelection {UserId= 2,GameSpreadId= 73,Bet= 2,PickTeamId= 15},
                 new UserGameSelection {UserId= 2,GameSpreadId= 74,Bet= 2,PickTeamId= 10},
                 new UserGameSelection {UserId= 2,GameSpreadId= 75,Bet= 1,PickTeamId= 26},
                 new UserGameSelection {UserId= 3,GameSpreadId= 62,Bet= 2,PickTeamId= 13},
                 new UserGameSelection {UserId= 3,GameSpreadId= 63,Bet= 1,PickTeamId= 29},
                 new UserGameSelection {UserId= 3,GameSpreadId= 64,Bet= 1,PickTeamId= 20},
                 new UserGameSelection {UserId= 3,GameSpreadId= 65,Bet= 1,PickTeamId= 23},
                 new UserGameSelection {UserId= 3,GameSpreadId= 66,Bet= 1,PickTeamId= 16},
                 new UserGameSelection {UserId= 3,GameSpreadId= 67,Bet= 3,PickTeamId= 22},
                 new UserGameSelection {UserId= 3,GameSpreadId= 68,Bet= 3,PickTeamId= 19},
                 new UserGameSelection {UserId= 3,GameSpreadId= 69,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameSpreadId= 70,Bet= 1,PickTeamId= 24},
                 new UserGameSelection {UserId= 3,GameSpreadId= 71,Bet= 1,PickTeamId= 25},
                 new UserGameSelection {UserId= 3,GameSpreadId= 72,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameSpreadId= 73,Bet= 1,PickTeamId= 15},
                 new UserGameSelection {UserId= 3,GameSpreadId= 74,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameSpreadId= 75,Bet= 1,PickTeamId= 26},
                 new UserGameSelection {UserId= 4,GameSpreadId= 62,Bet= 2,PickTeamId= 13},
                 new UserGameSelection {UserId= 4,GameSpreadId= 63,Bet= 1,PickTeamId= 9},
                 new UserGameSelection {UserId= 4,GameSpreadId= 64,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameSpreadId= 65,Bet= 1,PickTeamId= 27},
                 new UserGameSelection {UserId= 4,GameSpreadId= 66,Bet= 5,PickTeamId= 16},
                 new UserGameSelection {UserId= 4,GameSpreadId= 67,Bet= 1,PickTeamId= 22},
                 new UserGameSelection {UserId= 4,GameSpreadId= 68,Bet= 1,PickTeamId= 7},
                 new UserGameSelection {UserId= 4,GameSpreadId= 69,Bet= 1,PickTeamId= 28},
                 new UserGameSelection {UserId= 4,GameSpreadId= 70,Bet= 1,PickTeamId= 3},
                 new UserGameSelection {UserId= 4,GameSpreadId= 71,Bet= 1,PickTeamId= 25},
                 new UserGameSelection {UserId= 4,GameSpreadId= 72,Bet= 1,PickTeamId= 4},
                 new UserGameSelection {UserId= 4,GameSpreadId= 73,Bet= 2,PickTeamId= 15},
                 new UserGameSelection {UserId= 4,GameSpreadId= 74,Bet= 1,PickTeamId= 33},
                 new UserGameSelection {UserId= 4,GameSpreadId= 75,Bet= 0,PickTeamId= 1}
            };

            return userGameSelections;
        }

        public List<UserGameResult> InitializeUserGameResults()
        {
            var userGameResults = new List<UserGameResult>
            {
                new UserGameResult {UserGameSelectionId = 1,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 2,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 3,BetResult= -1,BetPoints= -4},
                new UserGameResult {UserGameSelectionId = 4,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 5,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 6,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 7,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 8,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 9,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 10,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 11,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 12,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 13,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 14,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 15,BetResult= -1,BetPoints= -3},
                new UserGameResult {UserGameSelectionId = 16,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 17,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 18,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 19,BetResult= -1,BetPoints= -5},
                new UserGameResult {UserGameSelectionId = 20,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 21,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 22,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 23,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 24,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 25,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 26,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 27,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 28,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 29,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 30,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 31,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 32,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 33,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 34,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 35,BetResult= -1,BetPoints= -4},
                new UserGameResult {UserGameSelectionId = 36,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 37,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 38,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 39,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 40,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 41,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 42,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 43,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 44,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 45,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 46,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 47,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 48,BetResult= -1,BetPoints= -2},
                new UserGameResult {UserGameSelectionId = 49,BetResult= 1,BetPoints= 3},
                new UserGameResult {UserGameSelectionId = 50,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 51,BetResult= -1,BetPoints= -3},
                new UserGameResult {UserGameSelectionId = 52,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 53,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 54,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 55,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 56,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 57,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 58,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 59,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 60,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 61,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 62,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 63,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 64,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 65,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 66,BetResult= 1,BetPoints= 5},
                new UserGameResult {UserGameSelectionId = 67,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 68,BetResult= -1,BetPoints= -4},
                new UserGameResult {UserGameSelectionId = 69,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 70,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 71,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 72,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 73,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 74,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 75,BetResult= 1,BetPoints= 4},
                new UserGameResult {UserGameSelectionId = 76,BetResult= 1,BetPoints= 4},
                new UserGameResult {UserGameSelectionId = 77,BetResult= -1,BetPoints= -2},
                new UserGameResult {UserGameSelectionId = 78,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 79,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 80,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 81,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 82,BetResult= 1,BetPoints= 4},
                new UserGameResult {UserGameSelectionId = 83,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 84,BetResult= -1,BetPoints= -4},
                new UserGameResult {UserGameSelectionId = 85,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 86,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 87,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 88,BetResult= -1,BetPoints= -2},
                new UserGameResult {UserGameSelectionId = 89,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 90,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 91,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 92,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 93,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 94,BetResult= -1,BetPoints= -2},
                new UserGameResult {UserGameSelectionId = 95,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 96,BetResult= -1,BetPoints= -3},
                new UserGameResult {UserGameSelectionId = 97,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 98,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 99,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 100,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 101,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 102,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 103,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 104,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 105,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 106,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 107,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 108,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 109,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 110,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 111,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 112,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 113,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 114,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 115,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 116,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 117,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 118,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 119,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 120,BetResult= -1,BetPoints= -2},
                new UserGameResult {UserGameSelectionId = 121,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 122,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 123,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 124,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 125,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 126,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 127,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 128,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 129,BetResult= 1,BetPoints= 5},
                new UserGameResult {UserGameSelectionId = 130,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 131,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 132,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 133,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 134,BetResult= 1,BetPoints= 6},
                new UserGameResult {UserGameSelectionId = 135,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 136,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 137,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 138,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 139,BetResult= -1,BetPoints= -3},
                new UserGameResult {UserGameSelectionId = 140,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 141,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 142,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 143,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 144,BetResult= 1,BetPoints= 3},
                new UserGameResult {UserGameSelectionId = 145,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 146,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 147,BetResult= 1,BetPoints= 3},
                new UserGameResult {UserGameSelectionId = 148,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 149,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 150,BetResult= 1,BetPoints= 4},
                new UserGameResult {UserGameSelectionId = 151,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 152,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 153,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 154,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 155,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 156,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 157,BetResult= -1,BetPoints= -2},
                new UserGameResult {UserGameSelectionId = 158,BetResult= 1,BetPoints= 4},
                new UserGameResult {UserGameSelectionId = 159,BetResult= 1,BetPoints= 4},
                new UserGameResult {UserGameSelectionId = 160,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 161,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 162,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 163,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 164,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 165,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 166,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 167,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 168,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 169,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 170,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 171,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 172,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 173,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 174,BetResult= 1,BetPoints= 3},
                new UserGameResult {UserGameSelectionId = 175,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 176,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 177,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 178,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 179,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 180,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 181,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 182,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 183,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 184,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 185,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 186,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 187,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 188,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 189,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 190,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 191,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 192,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 193,BetResult= 1,BetPoints= 5},
                new UserGameResult {UserGameSelectionId = 194,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 195,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 196,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 197,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 198,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 199,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 200,BetResult= 1,BetPoints= 5},
                new UserGameResult {UserGameSelectionId = 201,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 202,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 203,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 204,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 205,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 206,BetResult= -1,BetPoints= -3},
                new UserGameResult {UserGameSelectionId = 207,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 208,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 209,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 210,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 211,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 212,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 213,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 214,BetResult= 1,BetPoints= 3},
                new UserGameResult {UserGameSelectionId = 215,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 216,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 217,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 218,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 219,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 220,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 221,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 222,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 223,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 224,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 225,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 226,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 227,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 228,BetResult= 1,BetPoints= 4},
                new UserGameResult {UserGameSelectionId = 229,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 230,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 231,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 232,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 233,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 234,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 235,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 236,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 237,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 238,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 239,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 240,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 241,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 242,BetResult= 1,BetPoints= 3},
                new UserGameResult {UserGameSelectionId = 243,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 244,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 245,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 246,BetResult= 1,BetPoints= 10},
                new UserGameResult {UserGameSelectionId = 247,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 248,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 249,BetResult= 1,BetPoints= 5},
                new UserGameResult {UserGameSelectionId = 250,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 251,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 252,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 253,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 254,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 255,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 256,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 257,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 258,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 259,BetResult= -1,BetPoints= -2},
                new UserGameResult {UserGameSelectionId = 260,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 261,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 262,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 263,BetResult= 1,BetPoints= 3},
                new UserGameResult {UserGameSelectionId = 264,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 265,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 266,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 267,BetResult= -1,BetPoints= -3},
                new UserGameResult {UserGameSelectionId = 268,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 269,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 270,BetResult= -1,BetPoints= -2},
                new UserGameResult {UserGameSelectionId = 271,BetResult= -1,BetPoints= -2},
                new UserGameResult {UserGameSelectionId = 272,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 273,BetResult= -1,BetPoints= -2},
                new UserGameResult {UserGameSelectionId = 274,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 275,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 276,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 277,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 278,BetResult= 1,BetPoints= 3},
                new UserGameResult {UserGameSelectionId = 279,BetResult= 1,BetPoints= 6},
                new UserGameResult {UserGameSelectionId = 280,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 281,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 282,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 283,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 284,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 285,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 286,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 287,BetResult= -1,BetPoints= -2},
                new UserGameResult {UserGameSelectionId = 288,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 289,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 290,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 291,BetResult= 1,BetPoints= 5},
                new UserGameResult {UserGameSelectionId = 292,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 293,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 294,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 295,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 296,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 297,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 298,BetResult= -1,BetPoints= -2},
                new UserGameResult {UserGameSelectionId = 299,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 300,BetResult= 0,BetPoints= 0}
            };

            return userGameResults;
        }
    }
}