using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Selectum.Models
{
    public class ModelDataInitializer
    {
        public List<User> InitializeUsers()
        {
            var users = new List<User>
            {
                new User {UserName="hunt27"},
                new User {UserName="hubie39"},
                new User {UserName="coot77"},
                new User {UserName="wally4"}
            };

            return users;
        }

        public List<UserToUserProfile> InitializeUserToUserProfiles()
        {
            var users = new List<UserToUserProfile>
            {
                new UserToUserProfile {UserId = 1, UserProfileId=1},
                new UserToUserProfile {UserId = 2, UserProfileId=2},
                new UserToUserProfile {UserId = 3, UserProfileId=3},
                new UserToUserProfile {UserId = 4, UserProfileId=4}
            };

            return users;
        }

        public List<Team> InitializeTeams()
        {
            var teams = new List<Team>
            {
                new Team { TeamLongName = "No Bet", TeamShortName = "X  "}, 
                new Team { TeamLongName = "NY Giants", TeamShortName = "NYG"}, 
                new Team { TeamLongName = "New England", TeamShortName = "NE "}, 
                new Team { TeamLongName = "Minnesota", TeamShortName = "MIN"}, 
                new Team { TeamLongName = "New Orleans", TeamShortName = "NO "}, 
                new Team { TeamLongName = "Buffalo", TeamShortName = "BUF"}, 
                new Team { TeamLongName = "Philadelphia", TeamShortName = "PHI"}, 
                new Team { TeamLongName = "Oakland", TeamShortName = "OAK"}, 
                new Team { TeamLongName = "Cincinnati", TeamShortName = "CIN"}, 
                new Team { TeamLongName = "Houston", TeamShortName = "HOU"}, 
                new Team { TeamLongName = "Dallas", TeamShortName = "DAL"}, 
                new Team { TeamLongName = "Washington", TeamShortName = "WAS"}, 
                new Team { TeamLongName = "Pittsburgh", TeamShortName = "PIT"}, 
                new Team { TeamLongName = "San Diego", TeamShortName = "SD "}, 
                new Team { TeamLongName = "San Francisco", TeamShortName = "SF "}, 
                new Team { TeamLongName = "Atlanta", TeamShortName = "ATL"}, 
                new Team { TeamLongName = "Carolina", TeamShortName = "CAR"}, 
                new Team { TeamLongName = "Chicago", TeamShortName = "CHI"}, 
                new Team { TeamLongName = "Detroit", TeamShortName = "DET"}, 
                new Team { TeamLongName = "NY Jets", TeamShortName = "NYJ"}, 
                new Team { TeamLongName = "Indianapolis", TeamShortName = "IND"},
                new Team { TeamLongName = "Baltimore", TeamShortName = "BAL"}, 
                new Team { TeamLongName = "Kansas City", TeamShortName = "KC "},
                new Team { TeamLongName = "Seattle", TeamShortName = "SEA"},
                new Team { TeamLongName = "Arizona", TeamShortName = "ARI"},
                new Team { TeamLongName = "Denver", TeamShortName = "DEN"}, 
                new Team { TeamLongName = "Tampa Bay", TeamShortName = "TB "},
                new Team { TeamLongName = "Miami", TeamShortName = "MIA"},
                new Team { TeamLongName = "Cleveland", TeamShortName = "CLE"}, 
                new Team { TeamLongName = "Jacksonville", TeamShortName = "JAC"},
                new Team { TeamLongName = "St. Louis", TeamShortName = "STL"},
                new Team { TeamLongName = "Tennessee", TeamShortName = "TEN"},
                new Team { TeamLongName = "Green Bay", TeamShortName = "GB "}
            };

            return teams;
        }

        public List<GameFilter> InitializeGameFilters()
        {
            var gameFilters = new List<GameFilter>
            {
                new GameFilter { GameFilterName = "Week 01", GameFilterStartDate = Convert.ToDateTime("9/4/2012"), GameFilterEndDate = Convert.ToDateTime("9/10/2012 23:59:59.997") },
                new GameFilter { GameFilterName = "Week 02", GameFilterStartDate = Convert.ToDateTime("9/11/2012"), GameFilterEndDate = Convert.ToDateTime("9/17/2012 23:59:59.997") },
                new GameFilter { GameFilterName = "Week 03", GameFilterStartDate = Convert.ToDateTime("9/18/2012"), GameFilterEndDate = Convert.ToDateTime("9/24/2012 23:59:59.997") },
                new GameFilter { GameFilterName = "Week 04", GameFilterStartDate = Convert.ToDateTime("9/25/2012"), GameFilterEndDate = Convert.ToDateTime("10/1/2012 23:59:59.997") },
                new GameFilter { GameFilterName = "Week 05", GameFilterStartDate = Convert.ToDateTime("10/2/2012"), GameFilterEndDate = Convert.ToDateTime("10/8/2012 23:59:59.997") },
                new GameFilter { GameFilterName = "Week 06", GameFilterStartDate = Convert.ToDateTime("10/9/2012"), GameFilterEndDate = Convert.ToDateTime("10/15/2012 23:59:59.997") },
                new GameFilter { GameFilterName = "Week 07", GameFilterStartDate = Convert.ToDateTime("10/16/2012"), GameFilterEndDate = Convert.ToDateTime("10/22/2012 23:59:59.997") },
                new GameFilter { GameFilterName = "Week 08", GameFilterStartDate = Convert.ToDateTime("10/23/2012"), GameFilterEndDate = Convert.ToDateTime("10/29/2012 23:59:59.997") },
                new GameFilter { GameFilterName = "Week 09", GameFilterStartDate = Convert.ToDateTime("10/30/2012"), GameFilterEndDate = Convert.ToDateTime("11/5/2012 23:59:59.997") },
                new GameFilter { GameFilterName = "Week 10", GameFilterStartDate = Convert.ToDateTime("11/6/2012"), GameFilterEndDate = Convert.ToDateTime("11/12/2012 23:59:59.997") },
                new GameFilter { GameFilterName = "Week 11", GameFilterStartDate = Convert.ToDateTime("11/13/2012"), GameFilterEndDate = Convert.ToDateTime("11/19/2012 23:59:59.997") },
                new GameFilter { GameFilterName = "Week 12", GameFilterStartDate = Convert.ToDateTime("11/20/2012"), GameFilterEndDate = Convert.ToDateTime("11/26/2012 23:59:59.997") },
                new GameFilter { GameFilterName = "Week 13", GameFilterStartDate = Convert.ToDateTime("11/27/2012"), GameFilterEndDate = Convert.ToDateTime("12/3/2012 23:59:59.997") },
                new GameFilter { GameFilterName = "Week 14", GameFilterStartDate = Convert.ToDateTime("12/4/2012"), GameFilterEndDate = Convert.ToDateTime("12/10/2012 23:59:59.997") },
                new GameFilter { GameFilterName = "Week 15", GameFilterStartDate = Convert.ToDateTime("12/11/2012"), GameFilterEndDate = Convert.ToDateTime("12/17/2012 23:59:59.997") },
                new GameFilter { GameFilterName = "Week 16", GameFilterStartDate = Convert.ToDateTime("12/18/2012"), GameFilterEndDate = Convert.ToDateTime("12/24/2012 23:59:59.997") },
                new GameFilter { GameFilterName = "Week 17", GameFilterStartDate = Convert.ToDateTime("12/25/2012"), GameFilterEndDate = Convert.ToDateTime("12/31/2012 23:59:59.997") },

            };

            return gameFilters;
        }

        public List<Game> InitializeGames()
        {
            var games = new List<Game>
            {
                new Game {  GameFilterId = 2,GameDateTime= Convert.ToDateTime("2012-09-13 20:20:00"), FavoriteTeamId= 33,UnderdogTeamId= 18,Spread=  Convert.ToDecimal(6),HomeTeam="F"}, 
                new Game {  GameFilterId = 2,GameDateTime= Convert.ToDateTime("2012-09-16 13:00:00"), FavoriteTeamId= 2,UnderdogTeamId= 27,Spread=  Convert.ToDecimal(7.5),HomeTeam="F"}, 
                new Game {  GameFilterId = 2,GameDateTime= Convert.ToDateTime("2012-09-16 13:00:00"), FavoriteTeamId= 3,UnderdogTeamId= 25,Spread=  Convert.ToDecimal(13.5),HomeTeam="F"}, 
                new Game {  GameFilterId = 2,GameDateTime= Convert.ToDateTime("2012-09-16 13:00:00"), FavoriteTeamId= 4,UnderdogTeamId= 21,Spread=  Convert.ToDecimal(1.5),HomeTeam="U" }, 
                new Game {  GameFilterId = 2,GameDateTime= Convert.ToDateTime("2012-09-16 13:00:00"), FavoriteTeamId= 5,UnderdogTeamId= 17,Spread=  Convert.ToDecimal(2.5),HomeTeam="U" }, 
                new Game {  GameFilterId = 2,GameDateTime= Convert.ToDateTime("2012-09-16 13:00:00"), FavoriteTeamId= 6,UnderdogTeamId= 23,Spread=  Convert.ToDecimal(3),HomeTeam="F"}, 
                new Game {  GameFilterId = 2,GameDateTime= Convert.ToDateTime("2012-09-16 13:00:00"), FavoriteTeamId= 7,UnderdogTeamId= 22,Spread=  Convert.ToDecimal(2.5),HomeTeam="F"}, 
                new Game {  GameFilterId = 2,GameDateTime= Convert.ToDateTime("2012-09-16 13:00:00"), FavoriteTeamId= 8,UnderdogTeamId= 28,Spread=  Convert.ToDecimal(2.5),HomeTeam="U" }, 
                new Game {  GameFilterId = 2,GameDateTime= Convert.ToDateTime("2012-09-16 13:00:00"), FavoriteTeamId= 9,UnderdogTeamId= 29,Spread=  Convert.ToDecimal(7),HomeTeam="F"},
                new Game {  GameFilterId = 2,GameDateTime= Convert.ToDateTime("2012-09-16 13:00:00"), FavoriteTeamId= 10,UnderdogTeamId= 30,Spread=  Convert.ToDecimal(7.5),HomeTeam="U" }, 
                new Game {  GameFilterId = 2,GameDateTime= Convert.ToDateTime("2012-09-16 16:05:00"), FavoriteTeamId= 11,UnderdogTeamId= 24,Spread=  Convert.ToDecimal(3),HomeTeam="U" },
                new Game {  GameFilterId = 2,GameDateTime= Convert.ToDateTime("2012-09-16 16:05:00"), FavoriteTeamId= 12,UnderdogTeamId= 31,Spread=  Convert.ToDecimal(3),HomeTeam="U" }, 
                new Game {  GameFilterId = 2,GameDateTime= Convert.ToDateTime("2012-09-16 16:25:00"), FavoriteTeamId= 13,UnderdogTeamId= 20,Spread=  Convert.ToDecimal(6),HomeTeam="F"}, 
                new Game {  GameFilterId = 2,GameDateTime= Convert.ToDateTime("2012-09-16 16:25:00"), FavoriteTeamId= 14,UnderdogTeamId= 32,Spread=  Convert.ToDecimal(6),HomeTeam="F"}, 
                new Game {  GameFilterId = 2,GameDateTime= Convert.ToDateTime("2012-09-16 20:20:00"), FavoriteTeamId= 15,UnderdogTeamId= 19,Spread=  Convert.ToDecimal(6.5),HomeTeam="F"},
                new Game {  GameFilterId = 2,GameDateTime= Convert.ToDateTime("2012-09-17 20:35:00"), FavoriteTeamId= 16,UnderdogTeamId= 26,Spread=  Convert.ToDecimal(3),HomeTeam="F"}, 
                new Game {  GameFilterId = 3,GameDateTime= Convert.ToDateTime("2012-09-20 20:20:00"), FavoriteTeamId= 17,UnderdogTeamId= 2,Spread=  Convert.ToDecimal(2.5),HomeTeam="F"}, 
                new Game {  GameFilterId = 3,GameDateTime= Convert.ToDateTime("2012-09-23 13:00:00"), FavoriteTeamId= 18,UnderdogTeamId= 31,Spread=  Convert.ToDecimal(7.5),HomeTeam="F"},
                new Game {  GameFilterId = 3,GameDateTime= Convert.ToDateTime("2012-09-23 13:00:00"), FavoriteTeamId= 11,UnderdogTeamId= 27,Spread=  Convert.ToDecimal(8),HomeTeam="F"}, 
                new Game {  GameFilterId = 3,GameDateTime= Convert.ToDateTime("2012-09-23 13:00:00"), FavoriteTeamId= 15,UnderdogTeamId= 4,Spread=  Convert.ToDecimal(6.5),HomeTeam="U" }, 
                new Game {  GameFilterId = 3,GameDateTime= Convert.ToDateTime("2012-09-23 13:00:00"), FavoriteTeamId= 19,UnderdogTeamId= 32,Spread=  Convert.ToDecimal(3.5),HomeTeam="U" }, 
                new Game {  GameFilterId = 3,GameDateTime= Convert.ToDateTime("2012-09-23 13:00:00"), FavoriteTeamId= 12,UnderdogTeamId= 9,Spread=  Convert.ToDecimal(3),HomeTeam="F"}, 
                new Game {  GameFilterId = 3,GameDateTime= Convert.ToDateTime("2012-09-23 13:00:00"), FavoriteTeamId= 20,UnderdogTeamId= 28,Spread=  Convert.ToDecimal(2.5),HomeTeam="U" }, 
                new Game {  GameFilterId = 3,GameDateTime= Convert.ToDateTime("2012-09-23 13:00:00"), FavoriteTeamId= 5,UnderdogTeamId= 23,Spread=  Convert.ToDecimal(9),HomeTeam="F"}, 
                new Game {  GameFilterId = 3,GameDateTime= Convert.ToDateTime("2012-09-23 13:00:00"), FavoriteTeamId= 6,UnderdogTeamId= 29,Spread=  Convert.ToDecimal(3),HomeTeam="U" }, 
                new Game {  GameFilterId = 3,GameDateTime= Convert.ToDateTime("2012-09-23 13:00:00"), FavoriteTeamId= 21,UnderdogTeamId= 30,Spread=  Convert.ToDecimal(3),HomeTeam="F"},
                new Game {  GameFilterId = 3,GameDateTime= Convert.ToDateTime("2012-09-23 16:05:00"), FavoriteTeamId= 7,UnderdogTeamId= 25,Spread=  Convert.ToDecimal(3.5),HomeTeam="U" },
                new Game {  GameFilterId = 3,GameDateTime= Convert.ToDateTime("2012-09-23 16:05:00"), FavoriteTeamId= 14,UnderdogTeamId= 16,Spread=  Convert.ToDecimal(3),HomeTeam="F"}, 
                new Game {  GameFilterId = 3,GameDateTime= Convert.ToDateTime("2012-09-23 16:25:00"), FavoriteTeamId= 10,UnderdogTeamId= 26,Spread=  Convert.ToDecimal(2),HomeTeam="U" }, 
                new Game {  GameFilterId = 3,GameDateTime= Convert.ToDateTime("2012-09-23 16:25:00"), FavoriteTeamId= 13,UnderdogTeamId= 8,Spread=  Convert.ToDecimal(4.5),HomeTeam="U" },
                new Game {  GameFilterId = 3,GameDateTime= Convert.ToDateTime("2012-09-23 20:25:00"), FavoriteTeamId= 22,UnderdogTeamId= 3,Spread=  Convert.ToDecimal(3),HomeTeam="F"}, 
                new Game {  GameFilterId = 3,GameDateTime= Convert.ToDateTime("2012-09-24 20:35:00"), FavoriteTeamId= 33,UnderdogTeamId= 24,Spread=  Convert.ToDecimal(3),HomeTeam="U" },
                new Game {  GameFilterId = 4,GameDateTime= Convert.ToDateTime("2012-09-27 20:20:00"), FavoriteTeamId= 22,UnderdogTeamId= 29,Spread=  Convert.ToDecimal(13),HomeTeam="F"},
                new Game {  GameFilterId = 4,GameDateTime= Convert.ToDateTime("2012-09-30 13:00:00"), FavoriteTeamId= 3,UnderdogTeamId= 6,Spread=  Convert.ToDecimal(4),HomeTeam="U" }, 
                new Game {  GameFilterId = 4,GameDateTime= Convert.ToDateTime("2012-09-30 13:00:00"), FavoriteTeamId= 19,UnderdogTeamId= 4,Spread=  Convert.ToDecimal(4),HomeTeam="F"}, 
                new Game {  GameFilterId = 4,GameDateTime= Convert.ToDateTime("2012-09-30 13:00:00"), FavoriteTeamId= 16,UnderdogTeamId= 17,Spread=  Convert.ToDecimal(7),HomeTeam="F"},
                new Game {  GameFilterId = 4,GameDateTime= Convert.ToDateTime("2012-09-30 13:00:00"), FavoriteTeamId= 15,UnderdogTeamId= 20,Spread=  Convert.ToDecimal(4),HomeTeam="U" },
                new Game {  GameFilterId = 4,GameDateTime= Convert.ToDateTime("2012-09-30 13:00:00"), FavoriteTeamId= 23,UnderdogTeamId= 14,Spread=  Convert.ToDecimal(1),HomeTeam="F"},
                new Game {  GameFilterId = 4,GameDateTime= Convert.ToDateTime("2012-09-30 13:00:00"), FavoriteTeamId= 10,UnderdogTeamId= 32,Spread=  Convert.ToDecimal(12),HomeTeam="F"}, 
                new Game {  GameFilterId = 4,GameDateTime= Convert.ToDateTime("2012-09-30 13:00:00"), FavoriteTeamId= 24,UnderdogTeamId= 31,Spread=  Convert.ToDecimal(2.5),HomeTeam="U" },
                new Game {  GameFilterId = 4,GameDateTime= Convert.ToDateTime("2012-09-30 16:05:00"), FavoriteTeamId= 25,UnderdogTeamId= 28,Spread=  Convert.ToDecimal(6.5),HomeTeam="F"}, 
                new Game {  GameFilterId = 4,GameDateTime= Convert.ToDateTime("2012-09-30 16:05:00"), FavoriteTeamId= 26,UnderdogTeamId= 8,Spread=  Convert.ToDecimal(6.5),HomeTeam="F"}, 
                new Game {  GameFilterId = 4,GameDateTime= Convert.ToDateTime("2012-09-30 16:05:00"), FavoriteTeamId= 9,UnderdogTeamId= 30,Spread=  Convert.ToDecimal(2),HomeTeam="U" }, 
                new Game {  GameFilterId = 4,GameDateTime= Convert.ToDateTime("2012-09-30 16:25:00"), FavoriteTeamId= 33,UnderdogTeamId= 5,Spread=  Convert.ToDecimal(8),HomeTeam="F"}, 
                new Game {  GameFilterId = 4,GameDateTime= Convert.ToDateTime("2012-09-30 16:25:00"), FavoriteTeamId= 27,UnderdogTeamId= 12,Spread=  Convert.ToDecimal(3),HomeTeam="F"},
                new Game {  GameFilterId = 4,GameDateTime= Convert.ToDateTime("2012-09-30 16:30:00"), FavoriteTeamId= 7,UnderdogTeamId= 2,Spread=  Convert.ToDecimal(2),HomeTeam="F"},
                new Game {  GameFilterId = 4,GameDateTime= Convert.ToDateTime("2012-10-01 20:35:00"), FavoriteTeamId= 11,UnderdogTeamId= 18,Spread=  Convert.ToDecimal(4),HomeTeam="F"},
                new Game {  GameFilterId = 5,GameDateTime= Convert.ToDateTime("2012-10-04 20:25:00"), FavoriteTeamId= 25,UnderdogTeamId= 31,Spread=  Convert.ToDecimal(1.5),HomeTeam="U" },
                new Game {  GameFilterId = 5,GameDateTime= Convert.ToDateTime("2012-10-07 13:00:00"), FavoriteTeamId= 16,UnderdogTeamId= 12,Spread=  Convert.ToDecimal(3),HomeTeam="U" },
                new Game {  GameFilterId = 5,GameDateTime= Convert.ToDateTime("2012-10-07 13:00:00"), FavoriteTeamId= 13,UnderdogTeamId= 7,Spread=  Convert.ToDecimal(3.5),HomeTeam="F"},
                new Game {  GameFilterId = 5,GameDateTime= Convert.ToDateTime("2012-10-07 13:00:00"), FavoriteTeamId= 33,UnderdogTeamId= 21,Spread=  Convert.ToDecimal(7),HomeTeam="U" }, 
                new Game {  GameFilterId = 5,GameDateTime= Convert.ToDateTime("2012-10-07 13:00:00"), FavoriteTeamId= 2,UnderdogTeamId= 29,Spread=  Convert.ToDecimal(9),HomeTeam="F"}, 
                new Game {  GameFilterId = 5,GameDateTime= Convert.ToDateTime("2012-10-07 16:25:00"), FavoriteTeamId= 4,UnderdogTeamId= 32,Spread=  Convert.ToDecimal(5.5),HomeTeam="F"},
                new Game {  GameFilterId = 5,GameDateTime= Convert.ToDateTime("2012-10-07 13:00:00"), FavoriteTeamId= 9,UnderdogTeamId= 28,Spread=  Convert.ToDecimal(3.5),HomeTeam="F"},
                new Game {  GameFilterId = 5,GameDateTime= Convert.ToDateTime("2012-10-07 13:00:00"), FavoriteTeamId= 22,UnderdogTeamId= 23,Spread=  Convert.ToDecimal(6),HomeTeam="U" }, 
                new Game {  GameFilterId = 5,GameDateTime= Convert.ToDateTime("2012-10-07 16:05:00"), FavoriteTeamId= 17,UnderdogTeamId= 24,Spread=  Convert.ToDecimal(3),HomeTeam="F"}, 
                new Game {  GameFilterId = 5,GameDateTime= Convert.ToDateTime("2012-10-07 16:05:00"), FavoriteTeamId= 18,UnderdogTeamId= 30,Spread=  Convert.ToDecimal(6),HomeTeam="U" }, 
                new Game {  GameFilterId = 5,GameDateTime= Convert.ToDateTime("2012-10-07 16:25:00"), FavoriteTeamId= 3,UnderdogTeamId= 26,Spread=  Convert.ToDecimal(6.5),HomeTeam="F"},
                new Game {  GameFilterId = 5,GameDateTime= Convert.ToDateTime("2012-10-07 16:25:00"), FavoriteTeamId= 15,UnderdogTeamId= 6,Spread=  Convert.ToDecimal(9.5),HomeTeam="F"}, 
                new Game {  GameFilterId = 5,GameDateTime= Convert.ToDateTime("2012-10-07 20:30:00"), FavoriteTeamId= 5,UnderdogTeamId= 14,Spread=  Convert.ToDecimal(3.5),HomeTeam="F"}, 
                new Game {  GameFilterId = 5,GameDateTime= Convert.ToDateTime("2012-10-08 20:35:00"), FavoriteTeamId= 10,UnderdogTeamId= 20,Spread=  Convert.ToDecimal(8),HomeTeam="U" }, 
                new Game {  GameFilterId = 6,GameDateTime= Convert.ToDateTime("2012-10-11 20:25:00"), FavoriteTeamId= 13,UnderdogTeamId= 32,Spread=  Convert.ToDecimal(6),HomeTeam="U" }, 
                new Game {  GameFilterId = 6,GameDateTime= Convert.ToDateTime("2012-10-14 13:00:00"), FavoriteTeamId= 9,UnderdogTeamId= 29,Spread=  Convert.ToDecimal(1),HomeTeam="U" },
                new Game {  GameFilterId = 6,GameDateTime= Convert.ToDateTime("2012-10-14 13:00:00"), FavoriteTeamId= 20,UnderdogTeamId= 21,Spread=  Convert.ToDecimal(3),HomeTeam="F"},
                new Game {  GameFilterId = 6,GameDateTime= Convert.ToDateTime("2012-10-14 13:00:00"), FavoriteTeamId= 27,UnderdogTeamId= 23,Spread=  Convert.ToDecimal(4),HomeTeam="F"},
                new Game {  GameFilterId = 6,GameDateTime= Convert.ToDateTime("2012-10-14 13:00:00"), FavoriteTeamId= 16,UnderdogTeamId= 8,Spread=  Convert.ToDecimal(9),HomeTeam="F"}, 
                new Game {  GameFilterId = 6,GameDateTime= Convert.ToDateTime("2012-10-14 13:00:00"), FavoriteTeamId= 22,UnderdogTeamId= 11,Spread=  Convert.ToDecimal(3.5),HomeTeam="F"},
                new Game {  GameFilterId = 6,GameDateTime= Convert.ToDateTime("2012-10-14 13:00:00"), FavoriteTeamId= 7,UnderdogTeamId= 19,Spread=  Convert.ToDecimal(4),HomeTeam="F"}, 
                new Game {  GameFilterId = 6,GameDateTime= Convert.ToDateTime("2012-10-14 13:00:00"), FavoriteTeamId= 28,UnderdogTeamId= 31,Spread=  Convert.ToDecimal(3.5),HomeTeam="F"}, 
                new Game {  GameFilterId = 6,GameDateTime= Convert.ToDateTime("2012-10-14 16:05:00"), FavoriteTeamId= 3,UnderdogTeamId= 24,Spread=  Convert.ToDecimal(3.5),HomeTeam="U" }, 
                new Game {  GameFilterId = 6,GameDateTime= Convert.ToDateTime("2012-10-14 16:05:00"), FavoriteTeamId= 25,UnderdogTeamId= 6,Spread=  Convert.ToDecimal(4.5),HomeTeam="F"}, 
                new Game {  GameFilterId = 6,GameDateTime= Convert.ToDateTime("2012-10-14 16:25:00"), FavoriteTeamId= 12,UnderdogTeamId= 4,Spread=  Convert.ToDecimal(2),HomeTeam="F"}, 
                new Game {  GameFilterId = 6,GameDateTime= Convert.ToDateTime("2012-10-14 16:25:00"), FavoriteTeamId= 15,UnderdogTeamId= 2,Spread=  Convert.ToDecimal(6.5),HomeTeam="F"},
                new Game {  GameFilterId = 6,GameDateTime= Convert.ToDateTime("2012-10-14 20:30:00"), FavoriteTeamId= 10,UnderdogTeamId= 33,Spread=  Convert.ToDecimal(3.5),HomeTeam="F"},
                new Game {  GameFilterId = 6,GameDateTime= Convert.ToDateTime("2012-10-15 20:40:00"), FavoriteTeamId= 14,UnderdogTeamId= 26,Spread=  Convert.ToDecimal(1),HomeTeam="F"}
            };

            return games;
        }

        public List<UserGameSelection> InitializeUserGameSelections()
        {
            var userGameSelections = new List<UserGameSelection>
            {
                new UserGameSelection {UserId= 1,GameId= 1,Bet= 1,PickTeamId= 33}, 
                new UserGameSelection {UserId= 1,GameId= 2,Bet= 1,PickTeamId= 2}, 
                new UserGameSelection {UserId= 1,GameId= 3,Bet= 4,PickTeamId= 3}, 
                new UserGameSelection {UserId= 1,GameId= 4,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 1,GameId= 5,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 1,GameId= 6,Bet= 1,PickTeamId= 23}, 
                new UserGameSelection {UserId= 1,GameId= 7,Bet= 1,PickTeamId= 22}, 
                new UserGameSelection {UserId= 1,GameId= 8,Bet= 1,PickTeamId= 8}, 
                new UserGameSelection {UserId= 1,GameId= 9,Bet= 1,PickTeamId= 9}, 
                new UserGameSelection {UserId= 1,GameId= 10,Bet= 1,PickTeamId= 10}, 
                new UserGameSelection {UserId= 1,GameId= 11,Bet= 1,PickTeamId= 11},
                new UserGameSelection {UserId= 1,GameId= 12,Bet= 1,PickTeamId= 12}, 
                new UserGameSelection {UserId= 1,GameId= 13,Bet= 1,PickTeamId= 20}, 
                new UserGameSelection {UserId= 1,GameId= 14,Bet= 1,PickTeamId= 14}, 
                new UserGameSelection {UserId= 1,GameId= 15,Bet= 3,PickTeamId= 19}, 
                new UserGameSelection {UserId= 1,GameId= 16,Bet= 1,PickTeamId= 16}, 
                new UserGameSelection {UserId= 2,GameId= 1,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 2,GameId= 2,Bet= 1,PickTeamId= 2},
                new UserGameSelection {UserId= 2,GameId= 3,Bet= 5,PickTeamId= 3},
                new UserGameSelection {UserId= 2,GameId= 4,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 2,GameId= 5,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 2,GameId= 6,Bet= 0,PickTeamId= 1},
                new UserGameSelection {UserId= 2,GameId= 7,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 2,GameId= 8,Bet= 1,PickTeamId= 8}, 
                new UserGameSelection {UserId= 2,GameId= 9,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 2,GameId= 10,Bet= 2,PickTeamId= 10}, 
                new UserGameSelection {UserId= 2,GameId= 11,Bet= 1,PickTeamId= 11}, 
                new UserGameSelection {UserId= 2,GameId= 12,Bet= 1,PickTeamId= 12}, 
                new UserGameSelection {UserId= 2,GameId= 13,Bet= 0,PickTeamId= 1},
                new UserGameSelection {UserId= 2,GameId= 14,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 2,GameId= 15,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 2,GameId= 16,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 3,GameId= 1,Bet= 1,PickTeamId= 33}, 
                new UserGameSelection {UserId= 3,GameId= 2,Bet= 1,PickTeamId= 2},
                new UserGameSelection {UserId= 3,GameId= 3,Bet= 4,PickTeamId= 3},
                new UserGameSelection {UserId= 3,GameId= 4,Bet= 1,PickTeamId= 21},
                new UserGameSelection {UserId= 3,GameId= 5,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 3,GameId= 6,Bet= 0,PickTeamId= 1},
                new UserGameSelection {UserId= 3,GameId= 7,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 3,GameId= 8,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 3,GameId= 9,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 3,GameId= 10,Bet= 0,PickTeamId= 1},
                new UserGameSelection {UserId= 3,GameId= 11,Bet= 0,PickTeamId= 1},
                new UserGameSelection {UserId= 3,GameId= 12,Bet= 0,PickTeamId= 1},
                new UserGameSelection {UserId= 3,GameId= 13,Bet= 1,PickTeamId= 13},
                new UserGameSelection {UserId= 3,GameId= 14,Bet= 1,PickTeamId= 14},
                new UserGameSelection {UserId= 3,GameId= 15,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 3,GameId= 16,Bet= 2,PickTeamId= 26},
                new UserGameSelection {UserId= 4,GameId= 1,Bet= 3,PickTeamId= 33}, 
                new UserGameSelection {UserId= 4,GameId= 2,Bet= 1,PickTeamId= 2}, 
                new UserGameSelection {UserId= 4,GameId= 3,Bet= 3,PickTeamId= 3}, 
                new UserGameSelection {UserId= 4,GameId= 4,Bet= 0,PickTeamId= 1},
                new UserGameSelection {UserId= 4,GameId= 5,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 4,GameId= 6,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 4,GameId= 7,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 4,GameId= 8,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 4,GameId= 9,Bet= 1,PickTeamId= 9}, 
                new UserGameSelection {UserId= 4,GameId= 10,Bet= 1,PickTeamId= 10},
                new UserGameSelection {UserId= 4,GameId= 11,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 4,GameId= 12,Bet= 0,PickTeamId= 1}, 
                new UserGameSelection {UserId= 4,GameId= 13,Bet= 1,PickTeamId= 13},
                new UserGameSelection {UserId= 4,GameId= 14,Bet= 1,PickTeamId= 14},
                new UserGameSelection {UserId= 4,GameId= 15,Bet= 2,PickTeamId= 15}, 
                new UserGameSelection {UserId= 4,GameId= 16,Bet= 0,PickTeamId= 1},
                new UserGameSelection {UserId= 1,GameId= 17,Bet= 1,PickTeamId= 2}, 
                new UserGameSelection {UserId= 1,GameId= 18,Bet= 5,PickTeamId= 18},
                new UserGameSelection {UserId= 1,GameId= 19,Bet= 1,PickTeamId= 11},
                new UserGameSelection {UserId= 1,GameId= 20,Bet= 4,PickTeamId= 15},
                new UserGameSelection {UserId= 1,GameId= 21,Bet= 1,PickTeamId= 19},
                new UserGameSelection {UserId= 1,GameId= 22,Bet= 1,PickTeamId= 12}, 
                new UserGameSelection {UserId= 1,GameId= 23,Bet= 1,PickTeamId= 20}, 
                new UserGameSelection {UserId= 1,GameId= 24,Bet= 1,PickTeamId= 5}, 
                new UserGameSelection {UserId= 1,GameId= 25,Bet= 1,PickTeamId= 29},
                new UserGameSelection {UserId= 1,GameId= 26,Bet= 1,PickTeamId= 21},
                new UserGameSelection {UserId= 1,GameId= 27,Bet= 2,PickTeamId= 25},
                new UserGameSelection {UserId= 1,GameId= 28,Bet= 2,PickTeamId= 16},
                new UserGameSelection {UserId= 1,GameId= 29,Bet= 2,PickTeamId= 26}, 
                new UserGameSelection {UserId= 1,GameId= 30,Bet= 1,PickTeamId= 13},
                new UserGameSelection {UserId= 1,GameId= 31,Bet= 1,PickTeamId= 3},
                new UserGameSelection {UserId= 1,GameId= 32,Bet= 1,PickTeamId= 33},
                new UserGameSelection {UserId= 2,GameId= 17,Bet= 1,PickTeamId= 17},
                new UserGameSelection {UserId= 2,GameId= 18,Bet= 4,PickTeamId= 18},
                new UserGameSelection {UserId= 2,GameId= 19,Bet= 1,PickTeamId= 11},
                new UserGameSelection {UserId= 2,GameId= 20,Bet= 4,PickTeamId= 15},
                new UserGameSelection {UserId= 2,GameId= 21,Bet= 1,PickTeamId= 19},
                new UserGameSelection {UserId= 2,GameId= 22,Bet= 1,PickTeamId= 12},
                new UserGameSelection {UserId= 2,GameId= 23,Bet= 1,PickTeamId= 20}, 
                new UserGameSelection {UserId= 2,GameId= 24,Bet= 2,PickTeamId= 5}, 
                new UserGameSelection {UserId= 2,GameId= 25,Bet= 1,PickTeamId= 6},
                 new UserGameSelection {UserId= 2,GameId= 26,Bet= 1,PickTeamId= 21},
                 new UserGameSelection {UserId= 2,GameId= 27,Bet= 1,PickTeamId= 7},
                 new UserGameSelection {UserId= 2,GameId= 28,Bet= 1,PickTeamId= 14},
                 new UserGameSelection {UserId= 2,GameId= 29,Bet= 1,PickTeamId= 10},
                 new UserGameSelection {UserId= 2,GameId= 30,Bet= 2,PickTeamId= 13},
                 new UserGameSelection {UserId= 2,GameId= 31,Bet= 1,PickTeamId= 22},
                 new UserGameSelection {UserId= 2,GameId= 32,Bet= 3,PickTeamId= 33},
                 new UserGameSelection {UserId= 3,GameId= 17,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameId= 18,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameId= 19,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameId= 20,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameId= 21,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameId= 22,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameId= 23,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameId= 24,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameId= 25,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameId= 26,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameId= 27,Bet= 1,PickTeamId= 7},
                 new UserGameSelection {UserId= 3,GameId= 28,Bet= 1,PickTeamId= 14},
                 new UserGameSelection {UserId= 3,GameId= 29,Bet= 1,PickTeamId= 26},
                 new UserGameSelection {UserId= 3,GameId= 30,Bet= 1,PickTeamId= 8},
                 new UserGameSelection {UserId= 3,GameId= 31,Bet= 1,PickTeamId= 22},
                 new UserGameSelection {UserId= 3,GameId= 32,Bet= 1,PickTeamId= 33},
                 new UserGameSelection {UserId= 4,GameId= 17,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameId= 18,Bet= 2,PickTeamId= 18},
                 new UserGameSelection {UserId= 4,GameId= 19,Bet= 1,PickTeamId= 11},
                 new UserGameSelection {UserId= 4,GameId= 20,Bet= 1,PickTeamId= 15},
                 new UserGameSelection {UserId= 4,GameId= 21,Bet= 1,PickTeamId= 19},
                 new UserGameSelection {UserId= 4,GameId= 22,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameId= 23,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameId= 24,Bet= 2,PickTeamId= 5},
                 new UserGameSelection {UserId= 4,GameId= 25,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameId= 26,Bet= 1,PickTeamId= 21},
                 new UserGameSelection {UserId= 4,GameId= 27,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameId= 28,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameId= 29,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameId= 30,Bet= 1,PickTeamId= 13},
                 new UserGameSelection {UserId= 4,GameId= 31,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameId= 32,Bet= 1,PickTeamId= 33},
                 new UserGameSelection {UserId= 1,GameId= 33,Bet= 5,PickTeamId= 22},
                 new UserGameSelection {UserId= 1,GameId= 34,Bet= 1,PickTeamId= 3},
                 new UserGameSelection {UserId= 1,GameId= 35,Bet= 1,PickTeamId= 19},
                 new UserGameSelection {UserId= 1,GameId= 36,Bet= 2,PickTeamId= 16},
                 new UserGameSelection {UserId= 1,GameId= 37,Bet= 1,PickTeamId= 20},
                 new UserGameSelection {UserId= 1,GameId= 38,Bet= 3,PickTeamId= 14},
                 new UserGameSelection {UserId= 1,GameId= 39,Bet= 1,PickTeamId= 10},
                 new UserGameSelection {UserId= 1,GameId= 40,Bet= 1,PickTeamId= 24},
                 new UserGameSelection {UserId= 1,GameId= 41,Bet= 1,PickTeamId= 25},
                 new UserGameSelection {UserId= 1,GameId= 42,Bet= 1,PickTeamId= 26},
                 new UserGameSelection {UserId= 1,GameId= 43,Bet= 3,PickTeamId= 30},
                 new UserGameSelection {UserId= 1,GameId= 44,Bet= 1,PickTeamId= 33},
                 new UserGameSelection {UserId= 1,GameId= 45,Bet= 1,PickTeamId= 27},
                 new UserGameSelection {UserId= 1,GameId= 46,Bet= 1,PickTeamId= 2},
                 new UserGameSelection {UserId= 1,GameId= 47,Bet= 1,PickTeamId= 11},
                 new UserGameSelection {UserId= 2,GameId= 33,Bet= 3,PickTeamId= 22},
                 new UserGameSelection {UserId= 2,GameId= 34,Bet= 1,PickTeamId= 3},
                 new UserGameSelection {UserId= 2,GameId= 35,Bet= 1,PickTeamId= 19},
                 new UserGameSelection {UserId= 2,GameId= 36,Bet= 3,PickTeamId= 16},
                 new UserGameSelection {UserId= 2,GameId= 37,Bet= 1,PickTeamId= 15},
                 new UserGameSelection {UserId= 2,GameId= 38,Bet= 1,PickTeamId= 14},
                 new UserGameSelection {UserId= 2,GameId= 39,Bet= 4,PickTeamId= 10},
                 new UserGameSelection {UserId= 2,GameId= 40,Bet= 1,PickTeamId= 24},
                 new UserGameSelection {UserId= 2,GameId= 41,Bet= 1,PickTeamId= 25},
                 new UserGameSelection {UserId= 2,GameId= 42,Bet= 1,PickTeamId= 26},
                 new UserGameSelection {UserId= 2,GameId= 43,Bet= 1,PickTeamId= 9},
                 new UserGameSelection {UserId= 2,GameId= 44,Bet= 1,PickTeamId= 33},
                 new UserGameSelection {UserId= 2,GameId= 45,Bet= 1,PickTeamId= 12},
                 new UserGameSelection {UserId= 2,GameId= 46,Bet= 2,PickTeamId= 2},
                 new UserGameSelection {UserId= 2,GameId= 47,Bet= 2,PickTeamId= 18},
                 new UserGameSelection {UserId= 3,GameId= 33,Bet= 4,PickTeamId= 22},
                 new UserGameSelection {UserId= 3,GameId= 34,Bet= 1,PickTeamId= 3},
                 new UserGameSelection {UserId= 3,GameId= 35,Bet= 1,PickTeamId= 19},
                 new UserGameSelection {UserId= 3,GameId= 36,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameId= 37,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameId= 38,Bet= 1,PickTeamId= 14},
                 new UserGameSelection {UserId= 3,GameId= 39,Bet= 1,PickTeamId= 10},
                 new UserGameSelection {UserId= 3,GameId= 40,Bet= 1,PickTeamId= 31},
                 new UserGameSelection {UserId= 3,GameId= 41,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameId= 42,Bet= 1,PickTeamId= 8},
                 new UserGameSelection {UserId= 3,GameId= 43,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameId= 44,Bet= 1,PickTeamId= 33},
                 new UserGameSelection {UserId= 3,GameId= 45,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameId= 46,Bet= 1,PickTeamId= 2},
                 new UserGameSelection {UserId= 3,GameId= 47,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameId= 33,Bet= 3,PickTeamId= 22},
                 new UserGameSelection {UserId= 4,GameId= 34,Bet= 1,PickTeamId= 3},
                 new UserGameSelection {UserId= 4,GameId= 35,Bet= 1,PickTeamId= 19},
                 new UserGameSelection {UserId= 4,GameId= 36,Bet= 1,PickTeamId= 16},
                 new UserGameSelection {UserId= 4,GameId= 37,Bet= 1,PickTeamId= 15},
                 new UserGameSelection {UserId= 4,GameId= 38,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameId= 39,Bet= 1,PickTeamId= 10},
                 new UserGameSelection {UserId= 4,GameId= 40,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameId= 41,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameId= 42,Bet= 1,PickTeamId= 26},
                 new UserGameSelection {UserId= 4,GameId= 43,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameId= 44,Bet= 1,PickTeamId= 33},
                 new UserGameSelection {UserId= 4,GameId= 45,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameId= 46,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameId= 47,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 1,GameId= 48,Bet= 1,PickTeamId= 25},
                 new UserGameSelection {UserId= 1,GameId= 49,Bet= 1,PickTeamId= 12},
                 new UserGameSelection {UserId= 1,GameId= 50,Bet= 1,PickTeamId= 13},
                 new UserGameSelection {UserId= 1,GameId= 51,Bet= 1,PickTeamId= 33},
                 new UserGameSelection {UserId= 1,GameId= 52,Bet= 5,PickTeamId= 2},
                 new UserGameSelection {UserId= 1,GameId= 53,Bet= 1,PickTeamId= 4},
                 new UserGameSelection {UserId= 1,GameId= 54,Bet= 1,PickTeamId= 9},
                 new UserGameSelection {UserId= 1,GameId= 55,Bet= 1,PickTeamId= 22},
                 new UserGameSelection {UserId= 1,GameId= 56,Bet= 1,PickTeamId= 17},
                 new UserGameSelection {UserId= 1,GameId= 57,Bet= 1,PickTeamId= 18},
                 new UserGameSelection {UserId= 1,GameId= 58,Bet= 1,PickTeamId= 3},
                 new UserGameSelection {UserId= 1,GameId= 59,Bet= 5,PickTeamId= 15},
                 new UserGameSelection {UserId= 1,GameId= 60,Bet= 1,PickTeamId= 14},
                 new UserGameSelection {UserId= 1,GameId= 61,Bet= 1,PickTeamId= 10},
                 new UserGameSelection {UserId= 2,GameId= 48,Bet= 1,PickTeamId= 25},
                 new UserGameSelection {UserId= 2,GameId= 49,Bet= 2,PickTeamId= 16},
                 new UserGameSelection {UserId= 2,GameId= 50,Bet= 1,PickTeamId= 13},
                 new UserGameSelection {UserId= 2,GameId= 51,Bet= 3,PickTeamId= 33},
                 new UserGameSelection {UserId= 2,GameId= 52,Bet= 2,PickTeamId= 2},
                 new UserGameSelection {UserId= 2,GameId= 53,Bet= 1,PickTeamId= 32},
                 new UserGameSelection {UserId= 2,GameId= 54,Bet= 1,PickTeamId= 28},
                 new UserGameSelection {UserId= 2,GameId= 55,Bet= 2,PickTeamId= 22},
                 new UserGameSelection {UserId= 2,GameId= 56,Bet= 1,PickTeamId= 17},
                 new UserGameSelection {UserId= 2,GameId= 57,Bet= 2,PickTeamId= 18},
                 new UserGameSelection {UserId= 2,GameId= 58,Bet= 1,PickTeamId= 3},
                 new UserGameSelection {UserId= 2,GameId= 59,Bet= 3,PickTeamId= 15},
                 new UserGameSelection {UserId= 2,GameId= 60,Bet= 1,PickTeamId= 5},
                 new UserGameSelection {UserId= 2,GameId= 61,Bet= 1,PickTeamId= 10},
                 new UserGameSelection {UserId= 3,GameId= 48,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameId= 49,Bet= 1,PickTeamId= 12},
                 new UserGameSelection {UserId= 3,GameId= 50,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameId= 51,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameId= 52,Bet= 1,PickTeamId= 2},
                 new UserGameSelection {UserId= 3,GameId= 53,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameId= 54,Bet= 1,PickTeamId= 28},
                 new UserGameSelection {UserId= 3,GameId= 55,Bet= 1,PickTeamId= 22},
                 new UserGameSelection {UserId= 3,GameId= 56,Bet= 1,PickTeamId= 24},
                 new UserGameSelection {UserId= 3,GameId= 57,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameId= 58,Bet= 1,PickTeamId= 26},
                 new UserGameSelection {UserId= 3,GameId= 59,Bet= 4,PickTeamId= 15},
                 new UserGameSelection {UserId= 3,GameId= 60,Bet= 1,PickTeamId= 14},
                 new UserGameSelection {UserId= 3,GameId= 61,Bet= 1,PickTeamId= 10},
                 new UserGameSelection {UserId= 4,GameId= 48,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameId= 49,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameId= 50,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameId= 51,Bet= 1,PickTeamId= 33},
                 new UserGameSelection {UserId= 4,GameId= 52,Bet= 1,PickTeamId= 2},
                 new UserGameSelection {UserId= 4,GameId= 53,Bet= 1,PickTeamId= 4},
                 new UserGameSelection {UserId= 4,GameId= 54,Bet= 1,PickTeamId= 9},
                 new UserGameSelection {UserId= 4,GameId= 55,Bet= 1,PickTeamId= 22},
                 new UserGameSelection {UserId= 4,GameId= 56,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameId= 57,Bet= 1,PickTeamId= 18},
                 new UserGameSelection {UserId= 4,GameId= 58,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameId= 59,Bet= 3,PickTeamId= 15},
                 new UserGameSelection {UserId= 4,GameId= 60,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameId= 61,Bet= 1,PickTeamId= 10},
                 new UserGameSelection {UserId= 1,GameId= 62,Bet= 1,PickTeamId= 13},
                 new UserGameSelection {UserId= 1,GameId= 63,Bet= 5,PickTeamId= 29},
                 new UserGameSelection {UserId= 1,GameId= 64,Bet= 1,PickTeamId= 20},
                 new UserGameSelection {UserId= 1,GameId= 65,Bet= 1,PickTeamId= 27},
                 new UserGameSelection {UserId= 1,GameId= 66,Bet= 5,PickTeamId= 16},
                 new UserGameSelection {UserId= 1,GameId= 67,Bet= 1,PickTeamId= 22},
                 new UserGameSelection {UserId= 1,GameId= 68,Bet= 1,PickTeamId= 19},
                 new UserGameSelection {UserId= 1,GameId= 69,Bet= 1,PickTeamId= 28},
                 new UserGameSelection {UserId= 1,GameId= 70,Bet= 1,PickTeamId= 24},
                 new UserGameSelection {UserId= 1,GameId= 71,Bet= 1,PickTeamId= 25},
                 new UserGameSelection {UserId= 1,GameId= 72,Bet= 1,PickTeamId= 4},
                 new UserGameSelection {UserId= 1,GameId= 73,Bet= 1,PickTeamId= 2},
                 new UserGameSelection {UserId= 1,GameId= 74,Bet= 1,PickTeamId= 10},
                 new UserGameSelection {UserId= 1,GameId= 75,Bet= 1,PickTeamId= 26},
                 new UserGameSelection {UserId= 2,GameId= 62,Bet= 2,PickTeamId= 13},
                 new UserGameSelection {UserId= 2,GameId= 63,Bet= 1,PickTeamId= 29},
                 new UserGameSelection {UserId= 2,GameId= 64,Bet= 1,PickTeamId= 20},
                 new UserGameSelection {UserId= 2,GameId= 65,Bet= 1,PickTeamId= 23},
                 new UserGameSelection {UserId= 2,GameId= 66,Bet= 3,PickTeamId= 16},
                 new UserGameSelection {UserId= 2,GameId= 67,Bet= 2,PickTeamId= 22},
                 new UserGameSelection {UserId= 2,GameId= 68,Bet= 1,PickTeamId= 7},
                 new UserGameSelection {UserId= 2,GameId= 69,Bet= 1,PickTeamId= 28},
                 new UserGameSelection {UserId= 2,GameId= 70,Bet= 3,PickTeamId= 3},
                 new UserGameSelection {UserId= 2,GameId= 71,Bet= 1,PickTeamId= 25},
                 new UserGameSelection {UserId= 2,GameId= 72,Bet= 1,PickTeamId= 4},
                 new UserGameSelection {UserId= 2,GameId= 73,Bet= 2,PickTeamId= 15},
                 new UserGameSelection {UserId= 2,GameId= 74,Bet= 2,PickTeamId= 10},
                 new UserGameSelection {UserId= 2,GameId= 75,Bet= 1,PickTeamId= 26},
                 new UserGameSelection {UserId= 3,GameId= 62,Bet= 2,PickTeamId= 13},
                 new UserGameSelection {UserId= 3,GameId= 63,Bet= 1,PickTeamId= 29},
                 new UserGameSelection {UserId= 3,GameId= 64,Bet= 1,PickTeamId= 20},
                 new UserGameSelection {UserId= 3,GameId= 65,Bet= 1,PickTeamId= 23},
                 new UserGameSelection {UserId= 3,GameId= 66,Bet= 1,PickTeamId= 16},
                 new UserGameSelection {UserId= 3,GameId= 67,Bet= 3,PickTeamId= 22},
                 new UserGameSelection {UserId= 3,GameId= 68,Bet= 3,PickTeamId= 19},
                 new UserGameSelection {UserId= 3,GameId= 69,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameId= 70,Bet= 1,PickTeamId= 24},
                 new UserGameSelection {UserId= 3,GameId= 71,Bet= 1,PickTeamId= 25},
                 new UserGameSelection {UserId= 3,GameId= 72,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameId= 73,Bet= 1,PickTeamId= 15},
                 new UserGameSelection {UserId= 3,GameId= 74,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 3,GameId= 75,Bet= 1,PickTeamId= 26},
                 new UserGameSelection {UserId= 4,GameId= 62,Bet= 2,PickTeamId= 13},
                 new UserGameSelection {UserId= 4,GameId= 63,Bet= 1,PickTeamId= 9},
                 new UserGameSelection {UserId= 4,GameId= 64,Bet= 0,PickTeamId= 1},
                 new UserGameSelection {UserId= 4,GameId= 65,Bet= 1,PickTeamId= 27},
                 new UserGameSelection {UserId= 4,GameId= 66,Bet= 5,PickTeamId= 16},
                 new UserGameSelection {UserId= 4,GameId= 67,Bet= 1,PickTeamId= 22},
                 new UserGameSelection {UserId= 4,GameId= 68,Bet= 1,PickTeamId= 7},
                 new UserGameSelection {UserId= 4,GameId= 69,Bet= 1,PickTeamId= 28},
                 new UserGameSelection {UserId= 4,GameId= 70,Bet= 1,PickTeamId= 3},
                 new UserGameSelection {UserId= 4,GameId= 71,Bet= 1,PickTeamId= 25},
                 new UserGameSelection {UserId= 4,GameId= 72,Bet= 1,PickTeamId= 4},
                 new UserGameSelection {UserId= 4,GameId= 73,Bet= 2,PickTeamId= 15},
                 new UserGameSelection {UserId= 4,GameId= 74,Bet= 1,PickTeamId= 33},
                 new UserGameSelection {UserId= 4,GameId= 75,Bet= 0,PickTeamId= 1}
            };

            return userGameSelections;
        }

        public List<UserGameResult> InitializeUserGameResults()
        {
            var userGameResults = new List<UserGameResult>
            {
                new UserGameResult {UserGameSelectionId = 1,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 2,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 3,BetResult= -1,BetPoints= -4},
                new UserGameResult {UserGameSelectionId = 4,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 5,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 6,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 7,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 8,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 9,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 10,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 11,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 12,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 13,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 14,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 15,BetResult= -1,BetPoints= -3},
                new UserGameResult {UserGameSelectionId = 16,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 17,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 18,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 19,BetResult= -1,BetPoints= -5},
                new UserGameResult {UserGameSelectionId = 20,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 21,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 22,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 23,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 24,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 25,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 26,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 27,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 28,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 29,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 30,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 31,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 32,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 33,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 34,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 35,BetResult= -1,BetPoints= -4},
                new UserGameResult {UserGameSelectionId = 36,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 37,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 38,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 39,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 40,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 41,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 42,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 43,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 44,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 45,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 46,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 47,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 48,BetResult= -1,BetPoints= -2},
                new UserGameResult {UserGameSelectionId = 49,BetResult= 1,BetPoints= 3},
                new UserGameResult {UserGameSelectionId = 50,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 51,BetResult= -1,BetPoints= -3},
                new UserGameResult {UserGameSelectionId = 52,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 53,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 54,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 55,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 56,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 57,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 58,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 59,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 60,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 61,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 62,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 63,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 64,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 65,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 66,BetResult= 1,BetPoints= 5},
                new UserGameResult {UserGameSelectionId = 67,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 68,BetResult= -1,BetPoints= -4},
                new UserGameResult {UserGameSelectionId = 69,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 70,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 71,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 72,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 73,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 74,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 75,BetResult= 1,BetPoints= 4},
                new UserGameResult {UserGameSelectionId = 76,BetResult= 1,BetPoints= 4},
                new UserGameResult {UserGameSelectionId = 77,BetResult= -1,BetPoints= -2},
                new UserGameResult {UserGameSelectionId = 78,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 79,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 80,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 81,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 82,BetResult= 1,BetPoints= 4},
                new UserGameResult {UserGameSelectionId = 83,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 84,BetResult= -1,BetPoints= -4},
                new UserGameResult {UserGameSelectionId = 85,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 86,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 87,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 88,BetResult= -1,BetPoints= -2},
                new UserGameResult {UserGameSelectionId = 89,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 90,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 91,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 92,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 93,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 94,BetResult= -1,BetPoints= -2},
                new UserGameResult {UserGameSelectionId = 95,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 96,BetResult= -1,BetPoints= -3},
                new UserGameResult {UserGameSelectionId = 97,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 98,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 99,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 100,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 101,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 102,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 103,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 104,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 105,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 106,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 107,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 108,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 109,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 110,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 111,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 112,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 113,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 114,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 115,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 116,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 117,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 118,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 119,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 120,BetResult= -1,BetPoints= -2},
                new UserGameResult {UserGameSelectionId = 121,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 122,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 123,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 124,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 125,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 126,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 127,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 128,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 129,BetResult= 1,BetPoints= 5},
                new UserGameResult {UserGameSelectionId = 130,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 131,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 132,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 133,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 134,BetResult= 1,BetPoints= 6},
                new UserGameResult {UserGameSelectionId = 135,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 136,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 137,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 138,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 139,BetResult= -1,BetPoints= -3},
                new UserGameResult {UserGameSelectionId = 140,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 141,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 142,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 143,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 144,BetResult= 1,BetPoints= 3},
                new UserGameResult {UserGameSelectionId = 145,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 146,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 147,BetResult= 1,BetPoints= 3},
                new UserGameResult {UserGameSelectionId = 148,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 149,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 150,BetResult= 1,BetPoints= 4},
                new UserGameResult {UserGameSelectionId = 151,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 152,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 153,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 154,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 155,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 156,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 157,BetResult= -1,BetPoints= -2},
                new UserGameResult {UserGameSelectionId = 158,BetResult= 1,BetPoints= 4},
                new UserGameResult {UserGameSelectionId = 159,BetResult= 1,BetPoints= 4},
                new UserGameResult {UserGameSelectionId = 160,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 161,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 162,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 163,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 164,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 165,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 166,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 167,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 168,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 169,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 170,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 171,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 172,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 173,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 174,BetResult= 1,BetPoints= 3},
                new UserGameResult {UserGameSelectionId = 175,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 176,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 177,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 178,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 179,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 180,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 181,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 182,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 183,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 184,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 185,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 186,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 187,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 188,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 189,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 190,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 191,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 192,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 193,BetResult= 1,BetPoints= 5},
                new UserGameResult {UserGameSelectionId = 194,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 195,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 196,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 197,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 198,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 199,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 200,BetResult= 1,BetPoints= 5},
                new UserGameResult {UserGameSelectionId = 201,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 202,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 203,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 204,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 205,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 206,BetResult= -1,BetPoints= -3},
                new UserGameResult {UserGameSelectionId = 207,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 208,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 209,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 210,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 211,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 212,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 213,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 214,BetResult= 1,BetPoints= 3},
                new UserGameResult {UserGameSelectionId = 215,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 216,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 217,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 218,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 219,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 220,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 221,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 222,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 223,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 224,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 225,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 226,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 227,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 228,BetResult= 1,BetPoints= 4},
                new UserGameResult {UserGameSelectionId = 229,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 230,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 231,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 232,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 233,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 234,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 235,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 236,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 237,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 238,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 239,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 240,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 241,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 242,BetResult= 1,BetPoints= 3},
                new UserGameResult {UserGameSelectionId = 243,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 244,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 245,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 246,BetResult= 1,BetPoints= 10},
                new UserGameResult {UserGameSelectionId = 247,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 248,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 249,BetResult= 1,BetPoints= 5},
                new UserGameResult {UserGameSelectionId = 250,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 251,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 252,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 253,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 254,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 255,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 256,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 257,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 258,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 259,BetResult= -1,BetPoints= -2},
                new UserGameResult {UserGameSelectionId = 260,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 261,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 262,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 263,BetResult= 1,BetPoints= 3},
                new UserGameResult {UserGameSelectionId = 264,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 265,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 266,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 267,BetResult= -1,BetPoints= -3},
                new UserGameResult {UserGameSelectionId = 268,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 269,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 270,BetResult= -1,BetPoints= -2},
                new UserGameResult {UserGameSelectionId = 271,BetResult= -1,BetPoints= -2},
                new UserGameResult {UserGameSelectionId = 272,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 273,BetResult= -1,BetPoints= -2},
                new UserGameResult {UserGameSelectionId = 274,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 275,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 276,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 277,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 278,BetResult= 1,BetPoints= 3},
                new UserGameResult {UserGameSelectionId = 279,BetResult= 1,BetPoints= 6},
                new UserGameResult {UserGameSelectionId = 280,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 281,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 282,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 283,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 284,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 285,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 286,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 287,BetResult= -1,BetPoints= -2},
                new UserGameResult {UserGameSelectionId = 288,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 289,BetResult= 0,BetPoints= 0},
                new UserGameResult {UserGameSelectionId = 290,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 291,BetResult= 1,BetPoints= 5},
                new UserGameResult {UserGameSelectionId = 292,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 293,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 294,BetResult= 1,BetPoints= 1},
                new UserGameResult {UserGameSelectionId = 295,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 296,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 297,BetResult= -1,BetPoints= -1},
                new UserGameResult {UserGameSelectionId = 298,BetResult= -1,BetPoints= -2},
                new UserGameResult {UserGameSelectionId = 299,BetResult= 1,BetPoints= 2},
                new UserGameResult {UserGameSelectionId = 300,BetResult= 0,BetPoints= 0}
            };

            return userGameResults;
        }
    }
}