INSERT Team(TeamLongName,TeamShortName,TeamOtherName) VALUES('No Bet','X  ','No Bet')
INSERT Team(TeamLongName,TeamShortName,TeamOtherName) VALUES('NY Giants','NYG','Giants')
INSERT Team(TeamLongName,TeamShortName,TeamOtherName) VALUES('New England','NE ','Patriots')
INSERT Team(TeamLongName,TeamShortName,TeamOtherName) VALUES('Minnesota','MIN','Vikings')
INSERT Team(TeamLongName,TeamShortName,TeamOtherName) VALUES('New Orleans','NO ','Saints')
INSERT Team(TeamLongName,TeamShortName,TeamOtherName) VALUES('Buffalo','BUF','Bills')
INSERT Team(TeamLongName,TeamShortName,TeamOtherName) VALUES('Philadelphia','PHI','Eagles')
INSERT Team(TeamLongName,TeamShortName,TeamOtherName) VALUES('Oakland','OAK','Raiders')
INSERT Team(TeamLongName,TeamShortName,TeamOtherName) VALUES('Cincinnati','CIN','Bengals')
INSERT Team(TeamLongName,TeamShortName,TeamOtherName) VALUES('Houston','HOU','Texans')
INSERT Team(TeamLongName,TeamShortName,TeamOtherName) VALUES('Dallas','DAL','Cowboys')
INSERT Team(TeamLongName,TeamShortName,TeamOtherName) VALUES('Washington','WAS','Redskins')
INSERT Team(TeamLongName,TeamShortName,TeamOtherName) VALUES('Pittsburgh','PIT','Steelers')
INSERT Team(TeamLongName,TeamShortName,TeamOtherName) VALUES('San Diego','SD ','Chargers')
INSERT Team(TeamLongName,TeamShortName,TeamOtherName) VALUES('San Francisco','SF ','49ers')
INSERT Team(TeamLongName,TeamShortName,TeamOtherName) VALUES('Atlanta','ATL','Falcons')
INSERT Team(TeamLongName,TeamShortName,TeamOtherName) VALUES('Carolina','CAR','Panthers')
INSERT Team(TeamLongName,TeamShortName,TeamOtherName) VALUES('Chicago','CHI','Bears')
INSERT Team(TeamLongName,TeamShortName,TeamOtherName) VALUES('Detroit','DET','Lions')
INSERT Team(TeamLongName,TeamShortName,TeamOtherName) VALUES('NY Jets','NYJ','Jets')
INSERT Team(TeamLongName,TeamShortName,TeamOtherName) VALUES('Indianapolis','IND','Colts')
INSERT Team(TeamLongName,TeamShortName,TeamOtherName) VALUES('Baltimore','BAL','Ravens')
INSERT Team(TeamLongName,TeamShortName,TeamOtherName) VALUES('Kansas City','KC ','Chiefs')
INSERT Team(TeamLongName,TeamShortName,TeamOtherName) VALUES('Seattle','SEA','Seahawks')
INSERT Team(TeamLongName,TeamShortName,TeamOtherName) VALUES('Arizona','ARI','Cardinals')
INSERT Team(TeamLongName,TeamShortName,TeamOtherName) VALUES('Denver','DEN','Broncos')
INSERT Team(TeamLongName,TeamShortName,TeamOtherName) VALUES('Tampa Bay','TB ','Buccaneers')
INSERT Team(TeamLongName,TeamShortName,TeamOtherName) VALUES('Miami','MIA','Dolphins')
INSERT Team(TeamLongName,TeamShortName,TeamOtherName) VALUES('Cleveland','CLE','Browns')
INSERT Team(TeamLongName,TeamShortName,TeamOtherName) VALUES('Jacksonville','JAC','Jaguars')
INSERT Team(TeamLongName,TeamShortName,TeamOtherName) VALUES('St. Louis','STL','Rams')
INSERT Team(TeamLongName,TeamShortName,TeamOtherName) VALUES('Tennessee','TEN','Titans')
INSERT Team(TeamLongName,TeamShortName,TeamOtherName) VALUES('Green Bay','GB ','Packers')